import test from 'node:test';
import assert from 'node:assert/strict';
import { EventQueue } from '../src/core/queue';
import { normalizeEndpoint } from '../src/core/api';
import type { KeyValue,QueuedEvent } from '../src/core/types';
class Memory implements KeyValue { data=new Map<string,string>(); async get(key:string){return this.data.get(key)??null;} async set(key:string,value:string){this.data.set(key,value);} async remove(key:string){this.data.delete(key);} }
function event(id:string):QueuedEvent{return {id,type:'CHECK_IN',client_time:'2026-10-08T08:00:00Z',device_id:'test',payload:{assignment_id:'assignment',lat:53.19,lng:45.01,accuracy:5,qr_token:'qr',offline:true},state:'PENDING',attempts:0,nextAttempt:0};}
test('A killed process resends the same durable event and time',async()=>{const store=new Memory();const original=event('checkin');store.data.set('events',JSON.stringify([{...original,state:'SENDING'}]));const delivered:any[]=[];const queue=new EventQueue(store,async value=>{delivered.push(value);return {id:'server'};});await queue.load();await queue.flush(true);assert.equal(delivered.length,1);assert.equal(delivered[0].id,original.id);assert.equal(delivered[0].client_time,original.client_time);assert.equal(queue.list()[0]?.state,'SYNCED');});
test('A lost response retries idempotently without changing evidence',async()=>{const store=new Memory();let calls=0;const sent:any[]=[];const queue=new EventQueue(store,async value=>{sent.push(value);if(++calls===1)throw new Error('disconnected');return {id:'one'};});await queue.load();await queue.add(event('one'));await queue.flush(true);assert.equal(queue.list()[0]?.state,'ERROR');await queue.flush(true);assert.deepEqual(sent[0].payload,sent[1].payload);assert.equal(queue.list()[0]?.state,'SYNCED');});
test('An attachment waits for its incident and a rejected action remains visible',async()=>{const store=new Memory();const sent:string[]=[];const queue=new EventQueue(store,async value=>{sent.push(value.id);if(value.id==='incident')throw Object.assign(new Error('assignment revoked'),{status:409});return {ok:true};});await queue.load();await queue.add({...event('incident'),type:'INCIDENT_CREATE'});await queue.add({...event('photo'),type:'UPLOAD',payload:{depends_on:'incident',file:{name:'Фото.jpg'}}});await queue.flush(true);assert.deepEqual(sent,['incident']);assert.equal(queue.list()[0]?.state,'BLOCKED');assert.equal(queue.list()[1]?.state,'PENDING');});
test('Concurrent sync calls deliver each action once',async()=>{let calls=0;const queue=new EventQueue(new Memory(),async()=>{calls++;await new Promise(resolve=>setTimeout(resolve,10));return {ok:true};});await queue.load();await queue.add(event('one'));await Promise.all([queue.flush(),queue.flush(),queue.flush()]);assert.equal(calls,1);});
test('An unsuccessful write never reports an event as durably queued',async()=>{const store=new Memory();const queue=new EventQueue(store,async()=>({ok:true}));await queue.load();store.set=async()=>{throw new Error('disk full');};await assert.rejects(queue.add(event('disk')));});
test('Production endpoint requires HTTPS and rejects embedded credentials',()=>{assert.equal(normalizeEndpoint('https://example.ru/portal/'),'https://example.ru/portal/demo-api.php');assert.throws(()=>normalizeEndpoint('http://example.ru'));assert.throws(()=>normalizeEndpoint('https://user:password@example.ru'));});
test('An incident and all attachments commit together or none commit',async()=>{const store=new Memory();const queue=new EventQueue(store,async()=>({ok:true}));await queue.load();const failed=store.set.bind(store);store.set=async()=>{throw new Error('disk full');};await assert.rejects(queue.addBatch([{...event('incident'),type:'INCIDENT_CREATE'},{...event('photo'),type:'UPLOAD',payload:{depends_on:'incident',file:{name:'Фото.jpg',fileKey:'private-photo'}}}]));assert.equal(queue.list().length,0);store.set=failed;await queue.flush(true);assert.equal(queue.list().length,0);});
test('A reopened queue retains uploaded files until the server acknowledgement',async()=>{const store=new Memory();const queue=new EventQueue(store,async()=>{throw new Error('offline');});await queue.load();await queue.addBatch([{...event('incident'),type:'INCIDENT_CREATE'},{...event('file'),type:'UPLOAD',payload:{depends_on:'incident',file:{name:'Файл.pdf',mime:'application/pdf',fileKey:'encrypted-file'}}}]);await queue.flush(true);const reopened=new EventQueue(store,async()=>({ok:true}));await reopened.load();assert.equal(reopened.list()[1]?.payload.file.fileKey,'encrypted-file');await reopened.flush(true);assert.equal(reopened.list()[1]?.state,'SYNCED');assert.equal(reopened.list()[1]?.payload.file.fileKey,undefined);});
test('A concurrent failed write cannot hide a server acknowledgement',async()=>{const store=new Memory();let acknowledge!:()=>void;let started!:()=>void;const ready=new Promise<void>(r=>{started=r;});const response=new Promise<void>(r=>{acknowledge=r;});const queue=new EventQueue(store,async()=>{started();await response;return{id:'accepted'};});await queue.load();await queue.add(event('first'));const flush=queue.flush(true);await ready;const write=store.set.bind(store);store.set=async()=>{throw new Error('disk full');};await assert.rejects(queue.add(event('second')));store.set=write;acknowledge();await flush;assert.equal(queue.list().length,1);assert.equal(queue.list()[0]?.state,'SYNCED');const again=new EventQueue(store,async()=>{throw new Error('must not resend');});await again.load();assert.equal(again.list()[0]?.result?.id,'accepted');});
test('A pasted portal page resolves to its API endpoint',()=>{assert.equal(normalizeEndpoint('https://example.ru/portal/demo.php?app=admin'),'https://example.ru/portal/demo-api.php');});
