@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
hide methods
class Notification
class NotificationTemplate
class NotificationDelivery
class CustomerReport
class CustomerReportVersion
class ReportAcknowledgement
class ExportJob
class AuditLog
class OutboxEvent
class IntegrationDelivery
NotificationTemplate "1" -- "*" Notification
Notification "1" -- "*" NotificationDelivery
CustomerReport "1" -- "*" CustomerReportVersion
CustomerReportVersion "1" -- "*" ReportAcknowledgement
OutboxEvent "1" -- "*" IntegrationDelivery
ExportJob .. AuditLog
Notification .. OutboxEvent
CustomerReportVersion .. OutboxEvent
@enduml
