<?php
declare(strict_types=1);
require __DIR__.'/boot.php';
$sessionDir=CHOPPRO_STORAGE_ROOT.'/owner-sessions';if(!is_dir($sessionDir))mkdir($sessionDir,0700,true);session_save_path($sessionDir);session_name('choppro_owner');session_set_cookie_params(['path'=>(CHOPPRO_HOST_BASE?:'').'/','httponly'=>true,'secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','samesite'=>'Strict']);ini_set('session.use_strict_mode','1');session_start();$_SESSION['csrf']??=bin2hex(random_bytes(32));
$site=require $loader->private.'/site.php';$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        if(!hash_equals($_SESSION['csrf'],$_POST['csrf']??''))throw new RuntimeException('Обновите страницу и повторите действие');
        $action=$_POST['action']??'';
        if($action==='login'){
            $key=hash('sha256',$_SERVER['REMOTE_ADDR']??'local');$file=$loader->private.'/owner-attempts.json';$lock=fopen($loader->private.'/owner.lock','c');flock($lock,LOCK_EX);$rates=$loader->json($file);$rate=$rates[$key]??['attempts'=>0,'until'=>time()+600];if($rate['until']<time())$rate=['attempts'=>0,'until'=>time()+600];$rate['attempts']++;$rates[$key]=$rate;$loader->atomic($file,json_encode($rates));flock($lock,LOCK_UN);fclose($lock);if($rate['attempts']>10)throw new RuntimeException('Слишком много попыток входа. Повторите через 10 минут');
            if(!password_verify($_POST['password']??'',$site['owner_password_hash']??''))throw new RuntimeException('Неверный пароль владельца');session_regenerate_id(true);$_SESSION['owner_until']=time()+3600;$_SESSION['csrf']=bin2hex(random_bytes(32));$message='Вход выполнен';
        }elseif($action==='logout'){unset($_SESSION['owner_until']);}
        else{
            if(($_SESSION['owner_until']??0)<time())throw new RuntimeException('Войдите как владелец портала');$_SESSION['owner_until']=time()+3600;
            if($action==='sync'){$result=$loader->sync(true);if(!empty($result['error']))throw new RuntimeException($result['error']);$message=$result['pending']??'Проверка GitHub завершена. Доступная версия подготовлена';}
            elseif($action==='database'){
                @set_time_limit(240);$loader->sync(true);$release=host_release('portal');require $release['path'].'/backend/src/Core/Autoloader.php';$config=\Choppro\Stage2\Config::load();$db=new \Choppro\Stage2\Db($config);$result=(new \Choppro\Stage2\Migrator($db,$config))->apply();$loader->promote();$loader->atomic(CHOPPRO_STORAGE_ROOT.'/last-migration.json',json_encode(['at'=>gmdate('c'),'release'=>$release['sha'],'result'=>$result],JSON_UNESCAPED_UNICODE));$message='БД актуализирована. Версия схемы: '.$result['version'].'. Организаций: '.$result['tenants'].', сотрудников: '.$result['employees'].', смен: '.$result['shifts'].'. '.($result['seeded']?'Тестовые данные созданы.':'Существующие данные сохранены.');
            }elseif($action==='worker'){$release=host_release('demo');require $release['path'].'/backend/src/Core/Autoloader.php';$config=\Choppro\Stage2\Config::load();$result=(new \Choppro\Stage2\Worker(new \Choppro\Stage2\Db($config),$config))->tick();$message='Обработка документов, напоминаний и неявок выполнена';}
            elseif($action==='rollback'){$s=$loader->state();if(empty($s['previous']))throw new RuntimeException('Предыдущей версии нет');$loader->path($s['previous']);$s['portal']=$s['previous'];$s['demo']=$s['previous'];$loader->atomic($loader->private.'/current.json',json_encode($s));$message='Переключено на предыдущий целый комплект. База не откатывалась';}
        }
    }catch(PDOException $e){$error='Не удалось выполнить операцию с БД. Проверьте доступ в приватных настройках хостинга. Текущая версия продолжает работать';error_log('CHOPPRO migrations: '.$e->getMessage());}
    catch(Throwable $e){$error=$e->getMessage();}
}
$owner=($_SESSION['owner_until']??0)>=time();$state=$loader->state();$sync=$loader->json($loader->private.'/sync.json');$schema=$loader->json(CHOPPRO_STORAGE_ROOT.'/schema.json');$escape=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
header('Content-Type: text/html; charset=utf-8');header('Cache-Control: no-store');header('X-Frame-Options: DENY');header('X-Content-Type-Options: nosniff');header("Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'");
?>
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Управление порталом · ЧОППРО</title><style>body{margin:0;background:#f2f5fa;color:#24344d;font:14px/1.6 system-ui,sans-serif}main{max-width:820px;margin:7vh auto;padding:28px}h1{font-size:29px;line-height:1.3}p,small{color:#7b8ba3}section{background:white;border:1px solid #e0e6ef;border-radius:11px;padding:25px;margin:20px 0}.btn{background:#169b8d;color:white;border:0;border-radius:7px;padding:11px 17px;font-weight:600;cursor:pointer;font-size:13px}a{color:#169b8d;text-decoration:none}input{border:1px solid #d7e1ec;border-radius:6px;padding:12px;font:inherit;width:100%;box-sizing:border-box;margin:10px 0 18px}.notice{padding:15px;border-radius:8px;background:#e6f5ee;color:#288569}.error{background:#fcebee;color:#ac485d}.row{display:flex;gap:10px;flex-wrap:wrap}.info{font-size:12px;color:#7f91a7;overflow-wrap:anywhere}code{font-size:11px}form{margin:0}hr{border:0;border-top:1px solid #edf0f5;margin:20px 0}</style></head><body><main><a href="<?=CHOPPRO_HOST_BASE?>/">← Портал проекта</a><h1>Управление порталом</h1><p>Актуальная версия из GitHub и подготовка общей базы демо.</p><?php if($message):?><div class="notice"><?=$escape($message)?></div><?php endif?><?php if($error):?><div class="notice error"><?=$escape($error)?></div><?php endif?>
<?php if(!$owner):?><section><h2>Вход владельца</h2><p>Пароль управления находится в инструкции внутри установочного архива.</p><form method="post"><input type="hidden" name="csrf" value="<?=$escape($_SESSION['csrf'])?>"><input type="hidden" name="action" value="login"><label>Пароль управления<input name="password" type="password" autocomplete="current-password" required></label><button class="btn">Войти</button></form></section>
<?php else:?><section id="database"><h2>Актуализировать БД</h2><p>Первый запуск создаст таблицы в существующей БД и наполнит систему тестовыми данными. Следующие запуски применяют только новые миграции.</p><form method="post"><input type="hidden" name="csrf" value="<?=$escape($_SESSION['csrf'])?>"><input type="hidden" name="action" value="database"><button class="btn">Актуализировать БД</button></form><hr><div class="info">Версия схемы: <?=$escape($schema['version']??0)?><br>Портал: <code><?=$escape($state['portal']??'')?></code><br>Демо: <code><?=$escape($state['demo']??'')?></code><br>Источник: Jebvo777/CHOPPRO · main</div></section><section><h2>Обновление и обработка</h2><p>Новые версии скачиваются автоматически. Переключение происходит после проверки полного комплекта и успешной проверки в GitHub Actions.</p><div class="row"><?php foreach(['sync'=>'Проверить GitHub сейчас','worker'=>'Обработать напоминания','rollback'=>'Предыдущая версия','logout'=>'Выйти']as$action=>$label):?><form method="post"><input type="hidden" name="csrf" value="<?=$escape($_SESSION['csrf'])?>"><input type="hidden" name="action" value="<?=$action?>"><button class="btn"><?=$label?></button></form><?php endforeach?></div><?php if(!empty($sync['error'])):?><p><?=$escape($sync['error'])?></p><?php endif?></section><?php endif?>
<section><h2>Отдельные приложения</h2><div class="row"><?php foreach(['admin'=>'Демо администратора','client'=>'Демо заказчика','platform'=>'Демо платформы','jobs'=>'Демо биржи труда']as$app=>$title):?><a class="btn" href="<?=CHOPPRO_HOST_BASE?>/demo.php?app=<?=$app?>" target="_blank" rel="noopener"><?=$title?> ↗</a><?php endforeach?></div></section></main></body></html>
