<?php
declare(strict_types=1);
namespace Choppro\Stage2;
final class Backup
{
    private const MAGIC="CHOPPRO-BACKUP-1\n";
    public function __construct(public Db $db,public array $config){}
    private function key():string{return hash('sha256','choppro-backup:'.$this->config['key'],true);}
    private function tables():array{return array_values(array_filter(array_column($this->db->all('SHOW TABLES'),0),fn($n)=>preg_match('/^cp_[a-z0-9_]+$/',$n)&&$n!=='cp_backup_runs'));}
    private function names():array{$out=[];foreach($this->db->all('SHOW TABLES')as$r){$n=array_values($r)[0];if(preg_match('/^cp_[a-z0-9_]+$/',$n)&&$n!=='cp_backup_runs')$out[]=$n;}sort($out);return$out;}
    private function schema():string{return hash('sha256',Support::json($this->db->all('SELECT version,checksum FROM cp_schema_migrations ORDER BY version')));}
    private function directory():string{$p=$this->config['storage'].'/backups';if(!is_dir($p))mkdir($p,0700,true);return$p;}
    private function path(string $id):string{if(!preg_match('/^[a-f0-9-]{36}$/',$id))throw new Problem(422,'BACKUP_INVALID','Некорректная копия');return$this->directory().'/'.$id.'.enc';}
    private function write($f,array $record,string $prefix,int &$counter):void
    {
        $raw=gzdeflate(Support::json($record),3);$iv=$prefix.pack('N',++$counter);$cipher=openssl_encrypt($raw,'aes-256-gcm',$this->key(),OPENSSL_RAW_DATA,$iv,$tag,pack('N',$counter));if($cipher===false)throw new \RuntimeException('Шифрование не выполнено');$chunk=$iv.$tag.$cipher;$bytes=pack('N',strlen($chunk)).$chunk;if(fwrite($f,$bytes)!==strlen($bytes))throw new \RuntimeException('Недостаточно места для копии');
    }
    private function records(string $path):\Generator
    {
        $f=fopen($path,'rb');try{if(fread($f,strlen(self::MAGIC))!==self::MAGIC)throw new \RuntimeException('Некорректный формат копии');$counter=0;$prefix=null;while(!feof($f)){$length=fread($f,4);if($length==='')break;if(strlen($length)!==4)throw new \RuntimeException('Копия прервана');$n=unpack('N',$length)[1];if($n<28||$n>16777216)throw new \RuntimeException('Некорректный блок');$data='';while(strlen($data)<$n&&!feof($f))$data.=fread($f,$n-strlen($data));if(strlen($data)!==$n)throw new \RuntimeException('Копия прервана');$iv=substr($data,0,12);$prefix??=substr($iv,0,8);if(!hash_equals($prefix.pack('N',++$counter),$iv))throw new \RuntimeException('Порядок блоков нарушен');$raw=openssl_decrypt(substr($data,28),'aes-256-gcm',$this->key(),OPENSSL_RAW_DATA,$iv,substr($data,12,16),pack('N',$counter));if($raw===false)throw new \RuntimeException('Копия изменена или ключ недоступен');$json=gzinflate($raw,16777216);if($json===false)throw new \RuntimeException('Некорректный блок');yield Support::decode($json);}}finally{fclose($f);}
    }
    public function listing():array{return['items'=>$this->db->all('SELECT id,status,sha256,bytes,counts,error,created_at,finished_at,restored_at FROM cp_backup_runs ORDER BY created_at DESC LIMIT 100'),'interval_minutes'=>15,'target_restore_hours'=>4,'encrypted'=>true,'key_location'=>'Закрытая конфигурация сервера','scheduler'=>'Фоновая обработка при обращениях и site-cron.php для непрерывного расписания'];}
    public function due():bool{return !$this->db->pdo->inTransaction()&&(int)(getenv('CHOPPRO_DISABLE_AUTO_BACKUP')?:0)!==1&&strtotime($this->db->scalar("SELECT MAX(finished_at) FROM cp_backup_runs WHERE status='READY'")?:'1970-01-01')<time()-900;}
    public function create():array
    {
        if($this->db->pdo->inTransaction())throw new Problem(409,'BACKUP_BUSY','Завершите текущую операцию');$lock='choppro:backup:'.$this->config['database']['name'];if((int)$this->db->scalar('SELECT GET_LOCK(?,0)',[$lock])!==1)throw new Problem(409,'BACKUP_BUSY','Копирование уже выполняется');$id=Support::uuid();$file=$this->path($id);$f=null;$counts=['tables'=>0,'rows'=>0,'files'=>0];$maintenance=fopen($this->config['storage'].'/maintenance.lock','c');if(!flock($maintenance,LOCK_EX|LOCK_NB)){fclose($maintenance);$this->db->run('SELECT RELEASE_LOCK(?)',[$lock]);throw new Problem(409,'BACKUP_BUSY','Дождитесь завершения рабочих запросов');}
        try{$this->db->run("INSERT INTO cp_backup_runs(id,status,created_at)VALUES(?,'RUNNING',UTC_TIMESTAMP())",[$id]);$f=fopen($file.'.tmp','xb');chmod($file.'.tmp',0600);fwrite($f,self::MAGIC);$prefix=random_bytes(8);$counter=0;$this->db->pdo->exec('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');$this->db->pdo->beginTransaction();$names=$this->names();$this->write($f,['kind'=>'header','version'=>1,'id'=>$id,'schema'=>$this->schema(),'tables'=>$names,'created_at'=>Support::now()],$prefix,$counter);
            foreach($names as$table){$columns=array_column($this->db->all('SHOW COLUMNS FROM `'.$table.'`'),'Field');$this->write($f,['kind'=>'table','name'=>$table,'columns'=>$columns],$prefix,$counter);$query=$this->db->run('SELECT * FROM `'.$table.'`');while($row=$query->fetch()){$this->write($f,['kind'=>'row','table'=>$table,'data'=>$row],$prefix,$counter);$counts['rows']++;}$counts['tables']++;}
            foreach(['uploads','reports']as$kind){$root=$this->config['storage'].'/'.$kind;if(!is_dir($root))continue;foreach(new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($root,\FilesystemIterator::SKIP_DOTS))as$entry){if(!$entry->isFile()||$entry->isLink())continue;$relative=$kind.'/'.substr($entry->getPathname(),strlen($root)+1);$this->safeFile($relative);$sha=hash_file('sha256',$entry->getPathname());$this->write($f,['kind'=>'file','path'=>$relative,'bytes'=>$entry->getSize(),'sha256'=>$sha],$prefix,$counter);$in=fopen($entry->getPathname(),'rb');try{while(!feof($in)){$data=fread($in,65536);if($data!=='')$this->write($f,['kind'=>'chunk','bytes'=>base64_encode($data)],$prefix,$counter);}}finally{fclose($in);}$this->write($f,['kind'=>'file_end'],$prefix,$counter);$counts['files']++;}}
            $this->write($f,['kind'=>'end','counts'=>$counts],$prefix,$counter);$this->db->pdo->commit();fflush($f);fclose($f);$f=null;if(!rename($file.'.tmp',$file))throw new \RuntimeException('Не удалось завершить копию');$sha=hash_file('sha256',$file);$this->db->run("UPDATE cp_backup_runs SET status='READY',sha256=?,bytes=?,counts=?,finished_at=UTC_TIMESTAMP() WHERE id=?",[$sha,filesize($file),Support::json($counts),$id]);$this->prune();return['id'=>$id,'status'=>'READY','sha256'=>$sha,'counts'=>$counts];
        }catch(\Throwable$e){if($this->db->pdo->inTransaction())$this->db->pdo->rollBack();if(is_resource($f))fclose($f);@unlink($file.'.tmp');$this->db->run("UPDATE cp_backup_runs SET status='FAILED',error=?,finished_at=UTC_TIMESTAMP() WHERE id=?",['Не удалось создать копию. Проверьте место и права хранения.',$id]);throw$e;}finally{flock($maintenance,LOCK_UN);fclose($maintenance);$this->db->run('SELECT RELEASE_LOCK(?)',[$lock]);}
    }
    private function safeFile(string $relative):void{if(!preg_match('~^(uploads|reports)/[a-f0-9-]{36}/[a-zA-Z0-9_.-]{1,150}$~',$relative)||str_contains($relative,'..'))throw new \RuntimeException('Некорректный путь в копии');}
    public function verify(string $id):array
    {
        $row=$this->db->one("SELECT * FROM cp_backup_runs WHERE id=? AND status='READY'",[$id]);$path=$this->path($id);if(!$row||!is_file($path)||!hash_equals($row['sha256'],hash_file('sha256',$path)))throw new Problem(409,'BACKUP_CORRUPTED','Копия отсутствует или изменена');$counts=['tables'=>0,'rows'=>0,'files'=>0];$header=null;$end=null;$file=null;$hash=null;$size=0;$tables=[];
        try{foreach($this->records($path)as$record){if($end!==null)throw new \RuntimeException('Данные после завершения');switch($record['kind']??''){
            case'header':if($header!==null||$counts['rows'])throw new \RuntimeException('Повтор заголовка');$header=$record;if($record['schema']!==$this->schema()||$record['tables']!==$this->names())throw new \RuntimeException('Копия другой версии структуры');break;
            case'table':$n=$record['name'];if(!$header||!in_array($n,$header['tables'],true)||isset($tables[$n])||$record['columns']!==array_column($this->db->all('SHOW COLUMNS FROM `'.$n.'`'),'Field'))throw new \RuntimeException('Структура копии не совпадает');$tables[$n]=$record['columns'];$counts['tables']++;break;
            case'row':if(!isset($tables[$record['table']])||array_keys($record['data'])!==$tables[$record['table']])throw new \RuntimeException('Некорректная строка');$counts['rows']++;break;
            case'file':if($file)throw new \RuntimeException('Файл не завершен');$this->safeFile($record['path']);$file=$record;$hash=hash_init('sha256');$size=0;break;
            case'chunk':if(!$file||($bytes=base64_decode($record['bytes'],true))===false)throw new \RuntimeException('Некорректный файл');hash_update($hash,$bytes);$size+=strlen($bytes);break;
            case'file_end':if(!$file||$size!==$file['bytes']||!hash_equals($file['sha256'],hash_final($hash)))throw new \RuntimeException('Файл изменен');$file=null;$counts['files']++;break;
            case'end':if($file||!$header||$record['counts']!==$counts||$counts['tables']!==count($header['tables']))throw new \RuntimeException('Копия не завершена');$end=$record;break;
            default:throw new \RuntimeException('Неизвестный блок');}}
            if(!$end)throw new \RuntimeException('Копия прервана');return['id'=>$id,'status'=>'VERIFIED','counts'=>$counts,'schema'=>$header['schema']];
        }catch(\Throwable$e){throw new Problem(409,'BACKUP_INVALID','Проверка копии не пройдена: '.$e->getMessage());}
    }
    private function removeDir(string $dir):void{if(!is_dir($dir))return;foreach(new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir,\FilesystemIterator::SKIP_DOTS),\RecursiveIteratorIterator::CHILD_FIRST)as$p){if($p->isDir()&&!$p->isLink())rmdir($p->getPathname());else unlink($p->getPathname());}rmdir($dir);}
    public function download(string $id):never
    {
        $this->verify($id);header('Content-Type: application/octet-stream');header('Content-Disposition: attachment; filename="choppro-backup-'.$id.'.enc"');header('Cache-Control: no-store');readfile($this->path($id));exit;
    }
    public function recover():void
    {
        $journal=$this->config['storage'].'/restore.json';if(!is_file($journal))return;$handle=fopen($this->config['storage'].'/maintenance.lock','c');if(!flock($handle,LOCK_EX|LOCK_NB)){fclose($handle);throw new Problem(503,'MAINTENANCE','Восстановление базы выполняется. Повторите позже.');}
        try{if(!is_file($journal))return;$r=Support::decode(file_get_contents($journal));if(!preg_match('/^rr_[a-f0-9]{8}_$/',$r['prefix']??'')||!preg_match('/^ro_[a-f0-9]{8}_$/',$r['old']??'')||!is_array($r['tables']??null))throw new \RuntimeException('Некорректный журнал восстановления');foreach($r['tables']as$n)if(!preg_match('/^cp_[a-z0-9_]+$/',$n))throw new \RuntimeException('Некорректная таблица');$all=[];foreach($this->db->all('SHOW TABLES')as$row)$all[]=array_values($row)[0];$committed=in_array($r['old'].$r['tables'][0],$all,true)&&!in_array($r['prefix'].$r['tables'][0],$all,true);$committed=$committed||$r['phase']==='COMMITTED';$this->db->pdo->exec('SET FOREIGN_KEY_CHECKS=0');
            if($committed){foreach($r['tables']as$n)$this->db->pdo->exec('DROP TABLE IF EXISTS `'.$r['old'].$n.'`');foreach(['uploads','reports']as$kind)$this->removeDir($this->config['storage'].'/'.$r['old'].$kind);$this->db->run('UPDATE cp_sessions SET revoked_at=UTC_TIMESTAMP() WHERE revoked_at IS NULL');$this->db->run('UPDATE cp_backup_runs SET restored_at=UTC_TIMESTAMP() WHERE id=?',[$r['backup']]);}
            else{foreach(['uploads','reports']as$kind){$oldDir=$this->config['storage'].'/'.$r['old'].$kind;if(is_dir($oldDir)){$this->removeDir($this->config['storage'].'/'.$kind);rename($oldDir,$this->config['storage'].'/'.$kind);}}foreach($r['tables']as$n)$this->db->pdo->exec('DROP TABLE IF EXISTS `'.$r['prefix'].$n.'`');}
            $this->removeDir($this->config['storage'].'/'.$r['prefix'].'files');unlink($journal);
        }finally{$this->db->pdo->exec('SET FOREIGN_KEY_CHECKS=1');flock($handle,LOCK_UN);fclose($handle);}
    }
    private function prune():void{foreach($this->db->all("SELECT id FROM cp_backup_runs WHERE status='READY' AND created_at<DATE_SUB(UTC_TIMESTAMP(),INTERVAL 7 DAY) ORDER BY created_at DESC LIMIT 100")as$row){@unlink($this->path($row['id']));$this->db->run("UPDATE cp_backup_runs SET status='EXPIRED' WHERE id=?",[$row['id']]);}}
    public function restore(string $id):array
    {
        if($this->db->pdo->inTransaction())throw new Problem(409,'RESTORE_BUSY','Завершите текущую операцию');$verified=$this->verify($id);$started=microtime(true);$maintenance=fopen($this->config['storage'].'/maintenance.lock','c');if(!flock($maintenance,LOCK_EX|LOCK_NB)){fclose($maintenance);throw new Problem(409,'RESTORE_BUSY','Дождитесь завершения рабочих запросов');}$prefix='rr_'.bin2hex(random_bytes(4)).'_';$old='ro_'.bin2hex(random_bytes(4)).'_';$names=$this->names();$root=$this->config['storage'].'/'.$prefix.'files';$journal=$this->config['storage'].'/restore.json';$f=null;$renamed=false;$moved=[];
        try{mkdir($root,0700,true);$this->db->pdo->exec('SET FOREIGN_KEY_CHECKS=0');foreach($names as$n)$this->db->pdo->exec('CREATE TABLE `'.$prefix.$n.'` LIKE `'.$n.'`');$this->db->pdo->beginTransaction();foreach($this->records($this->path($id))as$r){if($r['kind']==='row'){$columns=array_keys($r['data']);$this->db->run('INSERT INTO `'.$prefix.$r['table'].'` (`'.implode('`,`',$columns).'`) VALUES ('.implode(',',array_fill(0,count($columns),'?')).')',array_values($r['data']));}elseif($r['kind']==='file'){$this->safeFile($r['path']);$p=$root.'/'.$r['path'];if(!is_dir(dirname($p)))mkdir(dirname($p),0700,true);$f=fopen($p,'xb');chmod($p,0600);}elseif($r['kind']==='chunk'){if(fwrite($f,base64_decode($r['bytes'],true))===false)throw new \RuntimeException('Не удалось восстановить файл');}elseif($r['kind']==='file_end'){fclose($f);$f=null;}}$this->db->pdo->commit();
            foreach($names as$n){$ddl=array_values($this->db->one('SHOW CREATE TABLE `'.$n.'`'))[1];preg_match_all('/CONSTRAINT `([^`]+)` (FOREIGN KEY[^\n]+?)(?:,?\n|\n?\))/',$ddl,$matches,PREG_SET_ORDER);foreach($matches as$m){$clause=rtrim($m[2],',');$clause=preg_replace_callback('/REFERENCES `([^`]+)`/',fn($x)=>'REFERENCES `'.$prefix.$x[1].'`',$clause);$this->db->pdo->exec('ALTER TABLE `'.$prefix.$n.'` ADD CONSTRAINT `'.$prefix.substr(hash('sha256',$m[1]),0,20).'` '.$clause);}}
            Support::atomic($journal,Support::json(['phase'=>'PREPARED','prefix'=>$prefix,'old'=>$old,'tables'=>$names,'backup'=>$id]));foreach(['uploads','reports']as$kind){if(!is_dir($root.'/'.$kind))mkdir($root.'/'.$kind,0700,true);if(is_dir($this->config['storage'].'/'.$kind)){if(!rename($this->config['storage'].'/'.$kind,$this->config['storage'].'/'.$old.$kind))throw new \RuntimeException('Файлы заняты');$moved[]=$kind;}if(!rename($root.'/'.$kind,$this->config['storage'].'/'.$kind))throw new \RuntimeException('Не удалось заменить файлы');}
            $renames=[];foreach($names as$n){$renames[]='`'.$n.'` TO `'.$old.$n.'`';$renames[]='`'.$prefix.$n.'` TO `'.$n.'`';}$this->db->pdo->exec('RENAME TABLE '.implode(',',$renames));$renamed=true;Support::atomic($journal,Support::json(['phase'=>'COMMITTED','prefix'=>$prefix,'old'=>$old,'tables'=>$names,'backup'=>$id]));$this->db->run("UPDATE cp_sessions SET revoked_at=UTC_TIMESTAMP() WHERE revoked_at IS NULL");$this->db->run('UPDATE cp_backup_runs SET restored_at=UTC_TIMESTAMP() WHERE id=?',[$id]);foreach($names as$n)$this->db->pdo->exec('DROP TABLE `'.$old.$n.'`');foreach(['uploads','reports']as$kind)$this->removeDir($this->config['storage'].'/'.$old.$kind);$this->removeDir($root);@unlink($journal);return$verified+['restored'=>true,'seconds'=>round(microtime(true)-$started,2),'sessions_revoked'=>true];
        }catch(\Throwable$e){if($this->db->pdo->inTransaction())$this->db->pdo->rollBack();if(is_resource($f))fclose($f);if(!$renamed){foreach(['uploads','reports']as$kind)if(in_array($kind,$moved,true)){$this->removeDir($this->config['storage'].'/'.$kind);rename($this->config['storage'].'/'.$old.$kind,$this->config['storage'].'/'.$kind);}foreach($names as$n)$this->db->pdo->exec('DROP TABLE IF EXISTS `'.$prefix.$n.'`');$this->removeDir($root);@unlink($journal);}throw$e;}finally{$this->db->pdo->exec('SET FOREIGN_KEY_CHECKS=1');flock($maintenance,LOCK_UN);fclose($maintenance);}
    }
}
