<?php
declare(strict_types=1);
namespace Choppro\Stage2;
final class IncidentWorkflow
{
    public function __construct(public Resources $r){}
    private function responsible(?string $id):?string
    {
        if(!$id)return null;$user=$this->r->access->reference('users',$id);if($user['status']!=='ACTIVE'||!(new Access($this->r->db(),$user))->allows('incidents.update'))throw new Problem(422,'RESPONSIBLE_INVALID','Выберите действующего сотрудника с правом работы с происшествиями');return$id;
    }
    public function listing(string $incident):array
    {
        $a=$this->r->access;$a->need('incidents.update');$a->find('incidents',$incident);return['items'=>$this->r->db()->all('SELECT t.*,u.name responsible_name FROM cp_incident_actions t LEFT JOIN cp_users u ON u.id=t.responsible_id WHERE t.tenant_id=? AND t.incident_id=? ORDER BY t.created_at',[$a->tenant(),$incident]),'resolutions'=>$this->r->db()->all('SELECT result,measures,responsible_id,created_at FROM cp_incident_resolutions WHERE tenant_id=? AND incident_id=? ORDER BY created_at',[$a->tenant(),$incident])];
    }
    public function action(string $incident,array $input):array
    {
        $a=$this->r->access;$a->need('incidents.update');$db=$this->r->db();return$db->transaction(function()use($incident,$input,$a,$db){$row=$a->find('incidents',$incident,false);$db->run('SELECT id FROM cp_incidents WHERE id=? FOR UPDATE',[$incident]);$row=$a->find('incidents',$incident,false);if($row['status']==='RESOLVED')throw new Problem(409,'INCIDENT_CLOSED','Происшествие уже закрыто');$old=isset($input['id'])?$db->one('SELECT * FROM cp_incident_actions WHERE id=? AND tenant_id=? AND incident_id=? FOR UPDATE',[$input['id'],$a->tenant(),$incident]):null;if(isset($input['id'])&&!$old)throw new Problem(404,'NOT_FOUND','Действие недоступно');if($old&&(int)($input['version']??0)!==(int)$old['version'])throw new Problem(409,'VERSION_CONFLICT','Действие изменилось. Обновите карточку');$data=array_replace($old??['name'=>'','responsible_id'=>null,'required'=>1,'status'=>'OPEN','result'=>'','deadline'=>null],array_intersect_key($input,array_flip(['name','responsible_id','required','status','result','deadline'])));$data['name']=trim($data['name']);if(mb_strlen($data['name'])<3||mb_strlen($data['name'])>200||!in_array($data['status'],['OPEN','DONE','CANCELLED'],true)||!in_array((int)$data['required'],[0,1],true))throw new Problem(422,'ACTION_INVALID','Заполните действие и его состояние');$data['responsible_id']=$this->responsible($data['responsible_id']);if($data['status']!=='OPEN'&&(mb_strlen(trim($data['result']??''))<10||!$data['responsible_id']))throw new Problem(422,'ACTION_RESULT_REQUIRED','Укажите результат и ответственного');if($data['status']==='CANCELLED'&&(int)$data['required'])throw new Problem(422,'REQUIRED_ACTION','Обязательное действие необходимо выполнить');if($data['deadline'])try{$data['deadline']=(new \DateTimeImmutable($data['deadline']))->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s');}catch(\Throwable){throw new Problem(422,'DATE_INVALID','Некорректный срок');}$id=$old['id']??Support::uuid();$values=[$data['name'],$data['responsible_id'],(int)$data['required'],$data['status'],$data['result'],$data['deadline'],$data['status']==='DONE'?Support::now():null];if($old)$db->run('UPDATE cp_incident_actions SET name=?,responsible_id=?,required=?,status=?,result=?,deadline=?,completed_at=?,updated_at=UTC_TIMESTAMP(),version=version+1 WHERE id=?',[...$values,$id]);else$db->run('INSERT INTO cp_incident_actions(name,responsible_id,required,status,result,deadline,completed_at,id,tenant_id,incident_id,created_at,updated_at)VALUES(?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())',[...$values,$id,$a->tenant(),$incident]);$a->audit('incident.action_saved','incidents',$incident,['action_id'=>$id,'status'=>$data['status']]);return['item'=>$db->one('SELECT * FROM cp_incident_actions WHERE id=?',[$id])];});
    }
    public function resolve(string $id,array $input):array
    {
        $a=$this->r->access;$a->need('incidents.update');$db=$this->r->db();return$db->transaction(function()use($id,$input,$a,$db){$row=$a->find('incidents',$id,false);$db->run('SELECT id FROM cp_incidents WHERE id=? FOR UPDATE',[$id]);$row=$a->find('incidents',$id,false);if((int)($input['version']??0)!==(int)$row['version'])throw new Problem(409,'VERSION_CONFLICT','Карточка изменилась. Обновите её');if($row['status']==='RESOLVED')throw new Problem(409,'INCIDENT_CLOSED','Происшествие уже закрыто');$responsible=$this->responsible($input['responsible_id']??null);foreach(['result','measures']as$key)if(mb_strlen(trim($input[$key]??''))<10||strlen($input[$key])>60000)throw new Problem(422,'RESOLUTION_REQUIRED','Укажите итог, принятые меры и ответственного');if(!$responsible)throw new Problem(422,'RESPONSIBLE_REQUIRED','Выберите ответственного');if($db->scalar("SELECT COUNT(*) FROM cp_incident_actions WHERE tenant_id=? AND incident_id=? AND required=1 AND status<>'DONE'",[$a->tenant(),$id]))throw new Problem(409,'ACTIONS_INCOMPLETE','Выполните все обязательные действия');$db->run('INSERT INTO cp_incident_resolutions(id,tenant_id,incident_id,actor_id,responsible_id,source_version,result,measures,created_at)VALUES(?,?,?,?,?,?,?,?,?)',[Support::uuid(),$a->tenant(),$id,$a->user['id'],$responsible,$row['version'],trim($input['result']),trim($input['measures']),Support::now()]);$this->r->write('incidents',$id,['status'=>'RESOLVED'],$row['version']);$a->audit('incident.resolved','incidents',$id,['responsible_id'=>$responsible,'source_version'=>$row['version']]);return['item'=>$a->safe('incidents',$a->find('incidents',$id))];});
    }
}
