<?php
declare(strict_types=1);
namespace Choppro\Stage2;
final class Reporting
{
    public const TYPES=['timesheet'=>'Табель план / факт','coverage'=>'Покрытие постов и неявки','patrols'=>'Обходы и контрольные точки','deadlines'=>'Сроки документов и договоров','incidents'=>'Происшествия','accounting'=>'Табель для кадрового учета'];
    public function __construct(public Resources $r){}
    private function bounds(array $q):array
    {
        $zone=Support::decode($this->r->db()->scalar('SELECT settings FROM cp_tenants WHERE id=?',[$this->r->access->tenant()])?:'{}')['timezone']??'Europe/Moscow';
        $from=(string)($q['from']??gmdate('Y-m-01'));$to=(string)($q['to']??gmdate('Y-m-t'));foreach([$from,$to]as$v)if(!preg_match('/^\d{4}-\d{2}-\d{2}$/',$v)||!strtotime($v)||gmdate('Y-m-d',strtotime($v))!==$v)throw new Problem(422,'DATE_INVALID','Выберите даты периода');$start=new \DateTimeImmutable($from,new \DateTimeZone($zone));$end=(new \DateTimeImmutable($to,new \DateTimeZone($zone)))->modify('+1 day');if($end<=$start||$end->getTimestamp()-$start->getTimestamp()>366*86400)throw new Problem(422,'DATE_RANGE','Период должен быть от одного дня до года');return[$start->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s'),$end->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s'),$from,$to];
    }
    public function data(string $type,array $q):array
    {
        $a=$this->r->access;$a->need('reporting.read');if(!isset(self::TYPES[$type]))throw new Problem(404,'REPORT_TYPE_INVALID','Отчет не найден');[$from,$to,$dateFrom,$dateTo]=$this->bounds($q);$db=$this->r->db();$rows=[];$headers=[];$summary=[];
        if(in_array($type,['timesheet','accounting'],true)){
            $a->need('attendance.read');$a->need('employees.read');[$where,$args]=$a->where('assignments');$where.=" AND s.published=1 AND s.status<>'CANCELLED' AND s.starts_at<? AND s.ends_at>?";array_push($args,$to,$from);if(!empty($q['facility_id'])){$where.=' AND f.id=?';$args[]=$q['facility_id'];}if(!empty($q['employee_id'])){$where.=' AND t.employee_id=?';$args[]=$q['employee_id'];}
            $items=$db->all("SELECT t.id,t.employee_id,t.status assignment_status,e.name employee_name,e.badge,s.starts_at,s.ends_at,p.name post_name,f.name facility_name,f.timezone,x.started_at,x.finished_at,x.status presence_status,(SELECT COUNT(*) FROM cp_attendance at WHERE at.assignment_id=t.id AND at.status='MANUAL_OVERRIDE') overrides,(SELECT COUNT(*) FROM cp_attendance at WHERE at.assignment_id=t.id AND at.status='REQUIRES_REVIEW' AND NOT EXISTS(SELECT 1 FROM cp_attendance ov WHERE ov.source_id=at.id)) review,EXISTS(SELECT 1 FROM cp_no_shows n WHERE n.assignment_id=t.id AND n.status='ACTIVE') no_show FROM cp_assignments t JOIN cp_employees e ON e.id=t.employee_id JOIN cp_shifts s ON s.id=t.shift_id JOIN cp_posts p ON p.id=s.post_id JOIN cp_facilities f ON f.id=p.facility_id LEFT JOIN cp_presence x ON x.assignment_id=t.id WHERE ".$where.' ORDER BY s.starts_at,e.name,t.id LIMIT 50001',$args);if(count($items)>50000)throw new Problem(422,'REPORT_TOO_LARGE','Сократите период отчета');$plan=0;$fact=0;
            $headers=$type==='accounting'?['Табельный номер','Сотрудник','Дата смены','Объект','Пост','План, ч','Факт, ч','Статус','Ручных решений']:['Сотрудник','Табельный номер','Объект','Пост','Начало смены','Окончание смены','Заступление','Завершение','План, ч','Факт, ч','Отклонение, ч','Статус','Ручных решений'];
            foreach($items as$i){$planned=in_array($i['assignment_status'],['ASSIGNED','CONFIRMED'],true)?max(0,min(strtotime($i['ends_at']),strtotime($to))-max(strtotime($i['starts_at']),strtotime($from)))/3600:0;$actual=$i['started_at']?max(0,min($i['finished_at']?strtotime($i['finished_at']):time(),strtotime($to))-max(strtotime($i['started_at']),strtotime($from)))/3600:0;$plan+=$planned;$fact+=$actual;$status=$i['review']?'Требует проверки':($i['no_show']?'Неявка':match($i['presence_status']){'COMPLETED'=>'Завершена','IN_PROGRESS'=>'В работе',default=>'Нет подтвержденного присутствия'});$local=fn($v)=>$v?(new \DateTimeImmutable($v,new \DateTimeZone('UTC')))->setTimezone(new \DateTimeZone($i['timezone']))->format('d.m.Y H:i'):'';
                $rows[]=$type==='accounting'?[$i['badge'],$i['employee_name'],$local($i['starts_at']),$i['facility_name'],$i['post_name'],round($planned,2),round($actual,2),$status,(int)$i['overrides']]:[$i['employee_name'],$i['badge'],$i['facility_name'],$i['post_name'],$local($i['starts_at']),$local($i['ends_at']),$local($i['started_at']),$local($i['finished_at']),round($planned,2),round($actual,2),round($actual-$planned,2),$status,(int)$i['overrides']];}
            $summary=['План, ч'=>round($plan,2),'Факт, ч'=>round($fact,2),'Назначений'=>count($rows)];
        }elseif($type==='coverage'){
            $a->need('shifts.read');[$where,$args]=$a->where('shifts');$where.=" AND t.published=1 AND t.status<>'CANCELLED' AND t.starts_at<? AND t.ends_at>?";array_push($args,$to,$from);if(!empty($q['facility_id'])){$where.=' AND f.id=?';$args[]=$q['facility_id'];}
            $items=$db->all("SELECT t.id,t.starts_at,t.ends_at,p.name post_name,p.headcount,f.name facility_name,(SELECT COUNT(*) FROM cp_assignments x WHERE x.shift_id=t.id AND x.deleted_at IS NULL AND x.status IN ('ASSIGNED','CONFIRMED')) assigned,(SELECT COUNT(*) FROM cp_presence x JOIN cp_assignments ax ON ax.id=x.assignment_id WHERE ax.shift_id=t.id AND ax.deleted_at IS NULL AND x.status IN ('IN_PROGRESS','COMPLETED')) present,(SELECT COUNT(*) FROM cp_no_shows n JOIN cp_assignments ax ON ax.id=n.assignment_id WHERE ax.shift_id=t.id AND n.status='ACTIVE') no_show FROM cp_shifts t JOIN cp_posts p ON p.id=t.post_id JOIN cp_facilities f ON f.id=p.facility_id WHERE ".$where.' ORDER BY t.starts_at,f.name,p.name LIMIT 50001',$args);if(count($items)>50000)throw new Problem(422,'REPORT_TOO_LARGE','Сократите период');$headers=['Объект','Пост','Начало','Окончание','Требуется','Назначено','Подтвержденное присутствие','Свободных мест','Неявки'];$required=0;$assigned=0;$present=0;$missing=0;foreach($items as$i){$required+=(int)$i['headcount'];$assigned+=min((int)$i['headcount'],(int)$i['assigned']);$present+=min((int)$i['headcount'],(int)$i['present']);$missing+=(int)$i['no_show'];$rows[]=[$i['facility_name'],$i['post_name'],$i['starts_at'].' UTC',$i['ends_at'].' UTC',(int)$i['headcount'],(int)$i['assigned'],(int)$i['present'],max(0,(int)$i['headcount']-(int)$i['assigned']),(int)$i['no_show']];}$summary=['Требуется'=>$required,'Назначено'=>$assigned,'Присутствие'=>$present,'Неявки'=>$missing,'Покрытие, %'=>$required?round(100*$assigned/$required,1):100];
        }elseif($type==='patrols'){
            $a->need('patrols.read');[$where,$args]=$a->where('patrols');$where.=' AND COALESCE(t.finished_at,t.created_at)>=? AND COALESCE(t.finished_at,t.created_at)<?';array_push($args,$from,$to);if(!empty($q['facility_id'])){$where.=' AND t.facility_id=?';$args[]=$q['facility_id'];}$items=$db->all('SELECT t.*,f.name facility_name FROM cp_patrols t JOIN cp_facilities f ON f.id=t.facility_id WHERE '.$where.' ORDER BY COALESCE(t.finished_at,t.created_at) DESC LIMIT 50000',$args);$headers=['Объект','Обход','Статус','План точек','Пройдено','Пропущено','Завершение','Отклонения и объяснения'];foreach($items as$i){$notes=$db->all("SELECT reasons,explanation FROM cp_patrol_scans WHERE tenant_id=? AND patrol_id=? AND status<>'VALID'",[$a->tenant(),$i['id']]);$rows[]=[$i['facility_name'],$i['name'],match($i['status']){'COMPLETED'=>'Завершен','IN_PROGRESS'=>'В работе','PARTIAL'=>'Частично',default=>'Пропущен'},(int)$i['total_points'],(int)$i['completed_points'],max(0,(int)$i['total_points']-(int)$i['completed_points']),$i['finished_at'],implode('; ',array_map(fn($n)=>implode(', ',Support::decode($n['reasons'])).': '.$n['explanation'],$notes))];}$summary=['Обходов'=>count($rows),'Пройдено точек'=>array_sum(array_column($rows,4)),'Пропущено точек'=>array_sum(array_column($rows,5))];
        }elseif($type==='deadlines'){
            $headers=['Раздел','Наименование','Объект / сотрудник','Срок','Статус'];foreach(['documents'=>'Документ','contracts'=>'Договор','compliance_tasks'=>'Контрольная задача']as$kind=>$label){if(!$a->allows($kind.'.read'))continue;[$where,$args]=$a->where($kind);$field=match($kind){'documents'=>'expires_at','contracts'=>'ends_at',default=>'deadline'};$where.=' AND t.'.$field.'>=? AND t.'.$field.'<?';array_push($args,$dateFrom,$to);if(!empty($q['status'])){$where.=' AND t.status=?';$args[]=$q['status'];}if(!empty($q['facility_id'])){$where.=match($kind){'documents'=>' AND EXISTS(SELECT 1 FROM cp_employees e WHERE e.id=t.employee_id AND e.facility_id=?)', 'contracts'=>' AND EXISTS(SELECT 1 FROM cp_facilities f WHERE f.contract_id=t.id AND f.id=?)',default=>' AND EXISTS(SELECT 1 FROM cp_facilities f WHERE f.contract_id=t.contract_id AND f.id=?)'};$args[]=$q['facility_id'];}$items=$db->all('SELECT t.* FROM cp_'.$kind.' t WHERE '.$where.' ORDER BY t.'.$field.' LIMIT 20000',$args);foreach($items as$i){$related=$kind==='documents'?$db->scalar('SELECT name FROM cp_employees WHERE id=?',[$i['employee_id']]):$db->scalar('SELECT GROUP_CONCAT(name SEPARATOR ", ") FROM cp_facilities WHERE contract_id=? AND tenant_id=? AND deleted_at IS NULL',[$kind==='contracts'?$i['id']:$i['contract_id'],$a->tenant()]);$rows[]=[$label,$i['name'],$related,$i[$field],self::status($i['status'])];}}$summary=['Сроков в периоде'=>count($rows)];
        }else{
            $a->need('incidents.read');[$where,$args]=$a->where('incidents');$where.=' AND t.created_at>=? AND t.created_at<?';array_push($args,$from,$to);if(!empty($q['facility_id'])){$where.=' AND t.facility_id=?';$args[]=$q['facility_id'];}if(!empty($q['severity'])){$where.=' AND t.severity=?';$args[]=$q['severity'];}$headers=['Объект','Происшествие','Важность','Статус','Дата','Описание','Принятые меры'];foreach($db->all('SELECT t.*,f.name facility_name,m.measures,m.client_time FROM cp_incidents t JOIN cp_facilities f ON f.id=t.facility_id LEFT JOIN cp_mobile_incidents m ON m.incident_id=t.id WHERE '.$where.' ORDER BY t.created_at DESC LIMIT 20000',$args)as$i)$rows[]=[$i['facility_name'],$i['name'],match($i['severity']){'CRITICAL'=>'Критическая','HIGH'=>'Высокая','LOW'=>'Низкая',default=>'Обычная'},self::status($i['status']),$i['client_time']??$i['created_at'],$i['description'],$i['measures']];$summary=['Происшествий'=>count($rows)];
        }
        if($type==='accounting'){$columns=(new OperationalSettings($this->r))->get()['accounting_columns'];$keys=array_keys(OperationalSettings::ACCOUNTING);$headers=array_column($columns,'name');$rows=array_map(fn($row)=>array_map(fn($c)=>$row[array_search($c['key'],$keys,true)],$columns),$rows);}
        return['type'=>$type,'title'=>self::TYPES[$type],'headers'=>$headers,'rows'=>$rows,'summary'=>$summary,'from'=>$dateFrom,'to'=>$dateTo,'generated_at'=>gmdate('c'),'total'=>count($rows)];
    }
    private static function status(string $value):string{return match($value){'VALID'=>'Действителен','EXPIRING'=>'Истекает','EXPIRED'=>'Истек','ACTIVE'=>'Активен','DRAFT'=>'Черновик','ENDED'=>'Завершен','OPEN'=>'Открыто','IN_PROGRESS'=>'В работе','RESOLVED'=>'Решено','OVERDUE'=>'Просрочено','DUE'=>'К исполнению','CONFIRMED'=>'Подтверждено','MARKED_SENT'=>'Отмечено отправленным',default=>'Требует проверки'};}
    public static function cell(mixed $v):mixed{if(!is_string($v))return$v;return preg_match('/^[\s\x00-\x20\x{FEFF}]*[=+@-]/u',$v)?"'".$v:$v;}
    public function export(string $type,array $q):never
    {
        $a=$this->r->access;$a->need('reporting.export');$data=$this->data($type,$q);$format=$q['format']??'csv';$a->audit('reporting.exported','reports',null,['type'=>$type,'rows'=>$data['total'],'format'=>$format,'from'=>$data['from'],'to'=>$data['to']]);header('Cache-Control: no-store');$name=$type.'-'.$data['from'].'-'.$data['to'];
        if($format==='pdf'){$lines=[$data['title'],'Период: '.$data['from'].' — '.$data['to'],'Сформировано: '.$data['generated_at']];foreach($data['summary']as$k=>$v)$lines[]=$k.': '.$v;$lines[]=implode(' | ',$data['headers']);foreach($data['rows']as$row)$lines[]=implode(' | ',array_map(fn($v)=>(string)$v,$row));header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="'.$name.'.pdf"');echo Pdf::render($lines);}
        elseif($format==='xlsx'){header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');header('Content-Disposition: attachment; filename="'.$name.'.xlsx"');echo Xlsx::render([$data['headers'],...array_map(fn($row)=>array_map([self::class,'cell'],$row),$data['rows'])],$data['title']);}
        elseif($format==='csv'){header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="'.$name.'.csv"');$f=fopen('php://output','w');fwrite($f,"\xEF\xBB\xBF");fputcsv($f,$data['headers'],';', '"','');foreach($data['rows']as$row)fputcsv($f,array_map([self::class,'cell'],$row),';','"','');fclose($f);}else throw new Problem(422,'FORMAT_INVALID','Выберите PDF, XLSX или CSV');exit;
    }
    public function monthly(array $input):array
    {
        $a=$this->r->access;$a->need('reports.create');$facility=$a->find('facilities',(string)($input['facility_id']??''));$period=(string)($input['period']??'');if(!preg_match('/^\d{4}-(0[1-9]|1[0-2])$/',$period))throw new Problem(422,'PERIOD_INVALID','Выберите месяц');$id=Support::uuid();$this->r->db()->run("INSERT IGNORE INTO cp_report_jobs(id,tenant_id,user_id,facility_id,period,status,created_at,updated_at)VALUES(?,?,?,?,?,'GENERATING',UTC_TIMESTAMP(),UTC_TIMESTAMP())",[$id,$a->tenant(),$a->user['id'],$facility['id'],$period]);$row=$this->r->db()->one('SELECT * FROM cp_report_jobs WHERE tenant_id=? AND facility_id=? AND period=?',[$a->tenant(),$facility['id'],$period]);if($row['status']==='FAILED')$this->r->db()->run("UPDATE cp_report_jobs SET status='GENERATING',attempts=0,error=NULL,updated_at=UTC_TIMESTAMP() WHERE id=?",[$row['id']]);$a->audit('report.generation_requested','report_jobs',$row['id'],['facility_id'=>$facility['id'],'period'=>$period]);return$row;
    }
    public static function schedule(Db $db,array $config):int
    {
        $count=0;foreach($db->all("SELECT id,settings FROM cp_tenants WHERE status='ACTIVE' AND deleted_at IS NULL")as$t){$settings=Support::decode($t['settings']);if(isset($settings['monthly_auto'])&&!$settings['monthly_auto'])continue;$u=$db->one("SELECT * FROM cp_users WHERE tenant_id=? AND role='tenant_admin' AND status='ACTIVE' AND deleted_at IS NULL ORDER BY created_at LIMIT 1",[$t['id']]);if(!$u||!(new Access($db,$u))->allows('reports.create'))continue;$date=new \DateTimeImmutable('first day of previous month',new \DateTimeZone($settings['timezone']??'Europe/Moscow'));$period=$date->format('Y-m');$from=$date->format('Y-m-01');$to=$date->modify('first day of next month')->format('Y-m-01');foreach($db->all("SELECT f.id FROM cp_facilities f WHERE f.tenant_id=? AND f.status='ACTIVE' AND f.deleted_at IS NULL AND EXISTS(SELECT 1 FROM cp_shifts s JOIN cp_posts p ON p.id=s.post_id WHERE p.facility_id=f.id AND s.published=1 AND s.deleted_at IS NULL AND s.status<>'CANCELLED' AND s.starts_at>=? AND s.starts_at<?)",[$t['id'],$from,$to])as$f)$count+=$db->run("INSERT IGNORE INTO cp_report_jobs(id,tenant_id,user_id,facility_id,period,status,created_at,updated_at)VALUES(?,?,?,?,?,'GENERATING',UTC_TIMESTAMP(),UTC_TIMESTAMP())",[Support::uuid(),$t['id'],$u['id'],$f['id'],$period])->rowCount();}return$count;
    }
    public static function work(Db $db,array $config):int
    {
        $count=0;foreach($db->all("SELECT * FROM cp_report_jobs WHERE status='GENERATING' AND attempts<5 ORDER BY created_at LIMIT 3")as$job){try{$db->transaction(function()use($db,$config,$job,&$count){$fresh=$db->one('SELECT * FROM cp_report_jobs WHERE id=? FOR UPDATE',[$job['id']]);if($fresh['status']!=='GENERATING')return;$u=$db->one("SELECT * FROM cp_users WHERE id=? AND status='ACTIVE' AND deleted_at IS NULL",[$job['user_id']]);if(!$u)throw new Problem(403,'AUTHOR_UNAVAILABLE','Доступ автора отозван');$r=new Resources(new Access($db,$u),$config);$f=$r->access->find('facilities',$job['facility_id']);$r->access->need('reports.create');$from=$job['period'].'-01';$to=(new \DateTimeImmutable($from))->format('Y-m-t');$parts=['Ежемесячный отчет по объекту '.$f['name'],'Период: '.$job['period']];
                $fake=['id'=>null,'tenant_id'=>$job['tenant_id'],'role'=>'tenant_admin','scopes'=>'[]'];$reporter=new self(new Resources(new Access($db,$fake),$config));$coverage=$reporter->data('coverage',['from'=>$from,'to'=>$to,'facility_id'=>$f['id']]);foreach($coverage['summary']as$k=>$v)$parts[]=$k.': '.$v;$parts[]='Обходы за период: '.$db->scalar('SELECT COUNT(*) FROM cp_patrols WHERE tenant_id=? AND facility_id=? AND COALESCE(finished_at,created_at)>=? AND COALESCE(finished_at,created_at)<?',[$job['tenant_id'],$f['id'],$from,(new \DateTimeImmutable($to))->modify('+1 day')->format('Y-m-d')]);foreach($db->all('SELECT name,description FROM cp_incidents WHERE tenant_id=? AND facility_id=? AND published=1 AND deleted_at IS NULL AND created_at>=? AND created_at<? ORDER BY created_at',[$job['tenant_id'],$f['id'],$from,(new \DateTimeImmutable($to))->modify('+1 day')->format('Y-m-d')])as$i)$parts[]=$i['name'].': '.$i['description'];$content=implode("\n",$parts);$pdf=Pdf::render($parts);$name='report-'.$job['id'].'.pdf';$directory=$config['storage'].'/reports/'.$job['tenant_id'];if(!is_dir($directory))mkdir($directory,0700,true);Support::atomic($directory.'/'.$name,$pdf);chmod($directory.'/'.$name,0600);
                $report=$r->insert('reports',['name'=>'Ежемесячный отчет · '.$f['name'],'facility_id'=>$f['id'],'customer_id'=>$f['customer_id'],'period'=>$job['period'],'status'=>'DRAFT','published'=>0,'content'=>$content,'internal_note'=>'','file_path'=>$name]);$db->run("UPDATE cp_report_jobs SET status='READY',report_id=?,attempts=attempts+1,error=NULL,updated_at=UTC_TIMESTAMP() WHERE id=?",[$report['id'],$job['id']]);$r->access->audit('report.generated','reports',$report['id'],['job_id'=>$job['id'],'facility_id'=>$f['id']]);$count++;});}catch(\Throwable$e){$db->run("UPDATE cp_report_jobs SET status='FAILED',attempts=attempts+1,error=?,updated_at=UTC_TIMESTAMP() WHERE id=?",['Не удалось сформировать отчет. Повторите после проверки доступа.',$job['id']]);error_log('CHOPPRO report '.$job['id'].' '.$e->getMessage());}}return$count;
    }
}
