<?php
declare(strict_types=1);
namespace Choppro\Stage2;
final class Schema
{
    public static function fields(string $kind): array { $all=self::all(); if(!isset($all[$kind])) throw new Problem(404,'NOT_FOUND','Раздел не найден'); return $all[$kind]; }
    public static function all(): array { static $v; return $v??=Support::decode(file_get_contents(dirname(__DIR__,2).'/database/stage2/resources.json')); }
    public static function names(): array { return ['personal_cards'=>'Личные карточки','no_shows'=>'Неявки','employees'=>'Сотрудники','document_types'=>'Типы документов','documents'=>'Документы сотрудников','licenses'=>'Лицензии','service_types'=>'Виды услуг','customers'=>'Заказчики','contracts'=>'Договоры','compliance_rules'=>'Правила контроля','compliance_tasks'=>'Контроль сроков','facilities'=>'Объекты','posts'=>'Посты','instructions'=>'Инструкции','qr_points'=>'QR-точки','shift_templates'=>'Шаблоны смен','shifts'=>'График смен','assignments'=>'Назначения','attendance'=>'Присутствие','vacancies'=>'Вакансии','applications'=>'Отклики','incidents'=>'Происшествия','patrols'=>'Обходы','reports'=>'Отчёты заказчика','notifications'=>'Уведомления','roles'=>'Роли и права','users'=>'Пользователи','audit'=>'Журнал аудита','holidays'=>'Рабочий календарь','contract_templates'=>'Шаблоны договоров']; }
    public static function references(): array { return ['employee_id'=>'employees','old_employee_id'=>'employees','new_employee_id'=>'employees','customer_id'=>'customers','facility_id'=>'facilities','post_id'=>'posts','contract_id'=>'contracts','license_id'=>'licenses','document_id'=>'documents','type_id'=>'document_types','instruction_id'=>'instructions','shift_id'=>'shifts','assignment_id'=>'assignments','rule_id'=>'compliance_rules','report_id'=>'reports','vacancy_id'=>'vacancies']; }
    public static function required(string $kind): array { return match($kind) { 'personal_cards'=>['name','employee_id','number'],'employees'=>['name','qualification'], 'documents'=>['name','employee_id','type_id'], 'contracts'=>['name','number','customer_id','license_id','starts_at','ends_at'], 'facilities'=>['name','customer_id','address','lat','lng','radius','timezone'], 'posts'=>['name','facility_id','qualification','headcount'], 'shifts'=>['name','post_id','starts_at','ends_at'], 'assignments'=>['name','shift_id','employee_id'], 'vacancies'=>['name','city','salary_from','salary_to','schedule','description'], default=>['name'] }; }
    public static function statuses(string $kind): array { return match($kind) { 'users'=>['ACTIVE','INVITED','BLOCKED','DISMISSED'],'personal_cards'=>['ACTIVE','SURRENDERED'],'employees'=>['ACTIVE','ON_LEAVE','DISMISSED'], 'documents'=>['PENDING_REVIEW','VALID','EXPIRING','EXPIRED','REJECTED'], 'contracts'=>['DRAFT','ACTIVE','ENDED'], 'compliance_tasks'=>['DRAFT','DUE','OVERDUE','MARKED_SENT','CONFIRMED','REJECTED'], 'shifts'=>['DRAFT','PUBLISHED','UNFILLED','COMPLETED','CANCELLED'], 'assignments'=>['ASSIGNED','CONFIRMED','DECLINED','REPLACED','CANCELLED'], 'attendance'=>['VALID','REQUIRES_REVIEW','MANUAL_OVERRIDE'], 'incidents'=>['OPEN','IN_PROGRESS','RESOLVED'], 'patrols'=>['COMPLETED','IN_PROGRESS','MISSED'], 'reports'=>['DRAFT','PUBLISHED'], 'vacancies'=>['DRAFT','PUBLISHED','CLOSED'], default=>['ACTIVE','INACTIVE'] }; }
    public static function labels(): array { return ['name'=>'Название','phone'=>'Телефон','email'=>'Email','qualification'=>'Разряд','badge'=>'Табельный номер','passport'=>'Документ, удостоверяющий личность','status'=>'Статус','hired_at'=>'Дата приёма','personal_card'=>'Личная карточка','facility_id'=>'Объект','employee_id'=>'Сотрудник','type_id'=>'Тип документа','number'=>'Номер','issued_at'=>'Дата выдачи','expires_at'=>'Действителен до','customer_id'=>'Заказчик','license_id'=>'Лицензия','starts_at'=>'Начало','ends_at'=>'Окончание','signed_at'=>'Дата подписания','amount'=>'Стоимость, ₽','services'=>'Коды услуг','ownership_proof'=>'Основание владения объектом','weapon_details'=>'Сведения об оружии','compensation'=>'Возмещение ущерба','legacy'=>'Переходный договор','address'=>'Адрес','city'=>'Город','lat'=>'Широта','lng'=>'Долгота','radius'=>'Радиус геозоны, м','timezone'=>'Часовой пояс','contact_name'=>'Контактное лицо','post_id'=>'Пост','mode'=>'Режим','headcount'=>'Численность','instruction'=>'Инструкция','instruction_version'=>'Версия инструкции','text'=>'Текст','revision'=>'Версия','token'=>'QR-токен','start_time'=>'Время начала','duration_hours'=>'Длительность, ч','weekdays'=>'Дни недели (1–7)','shift_id'=>'Смена','published'=>'Опубликовано','schedule'=>'График работы','salary_from'=>'Зарплата от, ₽','salary_to'=>'Зарплата до, ₽','description'=>'Описание','rule_code'=>'Код правила','rule_version'=>'Версия правила','service_code'=>'Код услуги','days'=>'Количество дней','working_days'=>'Рабочие дни','offset_hours'=>'Смещение, часов','valid_from'=>'Действует с','source'=>'Источник','template'=>'Шаблон','code'=>'Код','permissions'=>'Разрешения','required_fields'=>'Обязательные поля','duration_days'=>'Срок действия, дней','expiring_days'=>'Порог истечения, дней','deadline'=>'Срок исполнения','channel'=>'Канал отправки','receipt'=>'Номер подтверждения','attachment'=>'Вложение или исходящий номер','sent_at'=>'Время отправки','reason'=>'Причина','date'=>'Дата','is_working'=>'Рабочий день','message'=>'Сообщение','role'=>'Роль','customer_id'=>'Заказчик','scopes'=>'Доступные объекты','password'=>'Пароль']; }
    public static function defaults(string $kind): array { return match($kind) { 'employees'=>['status'=>'ACTIVE','qualification'=>4], 'document_types'=>['required_fields'=>['number','issued_at','expires_at'],'duration_days'=>365,'expiring_days'=>30], 'documents'=>['status'=>'PENDING_REVIEW','scan_status'=>'PENDING_SCAN'], 'licenses'=>['status'=>'ACTIVE','services'=>['physical','access']], 'contracts'=>['status'=>'DRAFT','services'=>['physical'],'legacy'=>0,'source_version'=>1], 'facilities'=>['status'=>'ACTIVE','timezone'=>'Europe/Moscow','radius'=>150,'lat'=>53.195878,'lng'=>45.018316], 'posts'=>['status'=>'ACTIVE','qualification'=>4,'headcount'=>1,'mode'=>'24/7','instruction_version'=>1], 'shifts'=>['status'=>'DRAFT','published'=>0], 'assignments'=>['status'=>'ASSIGNED'], 'vacancies'=>['status'=>'DRAFT','qualification'=>4,'pinned_rank'=>null], 'qr_points'=>['status'=>'ACTIVE','token'=>bin2hex(random_bytes(24))], 'compliance_tasks'=>['status'=>'DRAFT'], default=>['status'=>'ACTIVE'] }; }
}
