<?php
declare(strict_types=1);
namespace Choppro\Stage2;
final class Seeder
{
    public function __construct(public Db $db,public array $config) {}
    public static function id(string $key): string { $h=hash('sha256','choppro-demo-2:'.$key);return substr($h,0,8).'-'.substr($h,8,4).'-4'.substr($h,13,3).'-a'.substr($h,17,3).'-'.substr($h,20,12); }
    public function add(string $table,string $key,array $data): string
    {
        $id=self::id($key);$data=['id'=>$id,...$data,'created_at'=>$data['created_at']??Support::now()];
        if(!in_array($table,['sessions','challenges','audit','rate_limits'],true)){$data['updated_at']=$data['updated_at']??Support::now();$data['version']=1;}
        foreach($data as$k=>$v)if(is_array($v))$data[$k]=Support::json($v);
        $this->db->run('INSERT INTO cp_'.$table.' (`'.implode('`,`',array_keys($data)).'`) VALUES ('.implode(',',array_fill(0,count($data),'?')).')',array_values($data));return $id;
    }
    public function fill(): void
    {
        $hash=password_hash('Demo2026!',PASSWORD_ARGON2ID);$secret='JBSWY3DPEHPK3PXP';$mfa=Support::encrypt($secret,$this->config['key']);$date=new \DateTimeImmutable('today',new \DateTimeZone('Europe/Moscow'));
        $platform=$this->add('users','platform',['tenant_id'=>null,'name'=>'Алексей Волков','email'=>'platform@choppro.example','phone'=>'+79000000000','password_hash'=>$hash,'role'=>'platform_admin','scopes'=>[],'status'=>'ACTIVE','mfa_secret'=>$mfa,'mfa_enabled'=>1,'is_demo'=>1]);
        $companies=[['ОБЕРЕГ','obereg','Пенза',53.1959,45.0183],['ГАРАНТ','garant','Москва',55.7558,37.6173],['РУБЕЖ','rubezh','Самара',53.1955,50.1018],['ФОРПОСТ','forpost','Санкт-Петербург',59.9343,30.3351],['ВЕКТОР','vector','Нижний Новгород',56.2965,43.9361]];
        $first=['Александр','Дмитрий','Сергей','Андрей','Максим','Иван','Николай','Михаил','Артём','Владимир','Павел','Евгений','Алексей','Денис','Роман','Олег'];$last=['Иванов','Петров','Смирнов','Соколов','Кузнецов','Волков','Морозов','Фёдоров','Орлов','Новиков','Попов','Лебедев','Егоров','Козлов','Зайцев','Белов'];
        $objectNames=['Бизнес-центр «Панорама»','Логистический парк «Восток»','ТРЦ «Горизонт»','ЖК «Солнечный»','Завод «Импульс»','Склад «Север»','Школа № 28','Медицинский центр «Линия»','Гостиница «Сфера»','Автосалон «Мотор»','Офисный квартал «Деловой»','Производство «Технопарк»'];
        foreach($companies as$ti=>[$name,$slug,$city,$lat,$lng]){
            $settings=['timezone'=>'Europe/Moscow','language'=>'ru','reminder_days'=>[30,14,7,1],'default_radius'=>150,'late_minutes'=>15,'checkin_early_minutes'=>60,'checkin_late_minutes'=>120,'gps_max_accuracy'=>100,'weekly_hours_warning'=>48,'expiring_days'=>30];
            $tenant=$this->add('tenants','tenant-'.$ti,['name'=>'ЧОП «'.$name.'»','slug'=>$slug,'inn'=>'58000000'.str_pad((string)($ti+1),2,'0',STR_PAD_LEFT),'domain'=>$slug.'.choppro.example','status'=>'ACTIVE','settings'=>$settings,'features'=>['core'=>true,'compliance'=>true,'jobs'=>true]]);
            $dir=$this->config['storage'].'/uploads/'.$tenant;if(!is_dir($dir))mkdir($dir,0700,true);$fixture=dirname(__DIR__,2).'/database/stage2/demo-document.png';if(is_file($fixture))copy($fixture,$dir.'/demo-document.png');
            $users=[];foreach(['tenant_admin'=>'Елена Серова','hr'=>'Анна Миронова','operations'=>'Дмитрий Орлов','object_manager'=>'Сергей Макаров','customer'=>'Мария Крылова','guard'=>'Иван Петров']as$role=>$person){$email=match($role){'tenant_admin'=>'admin','object_manager'=>'manager',default=>$role}.'@'.$slug.'.example';$user=$this->add('users','user-'.$ti.'-'.$role,['tenant_id'=>$tenant,'name'=>$person,'email'=>$email,'phone'=>'+7900'.str_pad((string)($ti*100+array_search($role,array_keys(Access::ROLES))+1),7,'0',STR_PAD_LEFT),'password_hash'=>$hash,'role'=>$role,'scopes'=>[],'status'=>'ACTIVE','mfa_secret'=>$role==='tenant_admin'?$mfa:null,'mfa_enabled'=>$role==='tenant_admin'?1:0,'is_demo'=>1]);$users[$role]=$user;}
            foreach(Access::ROLES as$code=>$permissions)if($code!=='platform_admin')$this->add('roles','role-'.$ti.'-'.$code,['tenant_id'=>$tenant,'name'=>match($code){'tenant_admin'=>'Администратор ЧОП','hr'=>'Кадровик','operations'=>'Операционный руководитель','object_manager'=>'Начальник объекта','customer'=>'Представитель заказчика','guard'=>'Охранник'},'code'=>$code,'permissions'=>$permissions]);
            $types=[];foreach(['Удостоверение охранника','Медицинское заключение','Обучение и квалификация']as$di=>$type)$types[]=$this->add('document_types','type-'.$ti.'-'.$di,['tenant_id'=>$tenant,'name'=>$type,'required_fields'=>['number','issued_at','expires_at'],'duration_days'=>365,'expiring_days'=>30]);
            $license=$this->add('licenses','license-'.$ti,['tenant_id'=>$tenant,'name'=>'Лицензия ЧОП «'.$name.'»','number'=>'ЛЧО-'.$ti.'-2026-001','issued_at'=>'2024-01-15','expires_at'=>'2029-01-15','status'=>'ACTIVE','services'=>['physical','access','video','cargo','armed']]);
            foreach(['physical'=>'Физическая охрана','access'=>'Пропускной режим','video'=>'Видеонаблюдение','cargo'=>'Сопровождение грузов','armed'=>'Вооружённая охрана']as$code=>$service)$this->add('service_types','service-'.$ti.'-'.$code,['tenant_id'=>$tenant,'name'=>$service,'code'=>$code,'rule_version'=>1,'valid_from'=>'2026-01-01','source'=>'Согласуемый справочник пилотной организации']);
            $this->db->run('INSERT INTO cp_files(id,tenant_id,entity_type,entity_id,name,file_path,mime,sha256,scan_status,created_at)VALUES(?,?,?,?,?,?,?,?,?,?)',[self::id('file-license-'.$ti),$tenant,'licenses',$license,'Демонстрационное изображение лицензии','demo-document.png','image/png',hash_file('sha256',$fixture),'CLEAN',Support::now()]);
            $rules=[['contract_copy','Копия договора',null,5,1,0],['start_notice','Уведомление до начала услуг','physical',0,0,-12],['start_followup','Подтверждение начала','physical',5,0,0],['end_notice','Завершение услуг',null,5,0,0],['cargo_notice','Сопровождение груза','cargo',1,0,0],['staff_change','Изменение участников/руководителя',null,15,0,0]];
            $ruleIds=[];foreach($rules as$ri=>[$code,$label,$service,$days,$work,$offset])$ruleIds[]=$this->add('compliance_rules','rule-'.$ti.'-'.$ri,['tenant_id'=>$tenant,'name'=>$label,'rule_code'=>$code,'rule_version'=>1,'service_code'=>$service,'days'=>$days,'working_days'=>$work,'offset_hours'=>$offset,'valid_from'=>'2026-01-01','source'=>'Демонстрационный справочник. Требует утверждения ответственным специалистом.','template'=>'Организация {{tenant}}; договор {{contract}}; дата {{date}}.']);
            foreach(['2026-01-01','2026-01-02','2026-01-05','2026-01-06','2026-01-07','2026-01-08','2026-02-23','2026-03-09','2026-05-01','2026-05-11','2026-06-12','2026-11-04','2026-12-31']as$h)$this->add('holidays','holiday-'.$ti.'-'.$h,['tenant_id'=>$tenant,'name'=>'Демонстрационный нерабочий день','date'=>$h,'is_working'=>0]);
            $customers=[];for($ci=0;$ci<18;$ci++)$customers[]=$this->add('customers','customer-'.$ti.'-'.$ci,['tenant_id'=>$tenant,'name'=>['ООО «Регион Девелопмент»','АО «Промышленный альянс»','Группа «Логистик Про»','УК «Городские пространства»','ООО «Торговые решения»','МБУ «Образовательный центр»'][$ci%6].' · '.($ci+1),'inn'=>'770'.str_pad((string)($ti*100+$ci),7,'0',STR_PAD_LEFT),'contact_name'=>['Мария Крылова','Екатерина Новикова','Александр Белов'][$ci%3],'phone'=>'+7910'.str_pad((string)($ti*100+$ci+10),7,'0',STR_PAD_LEFT),'email'=>'office'.$ci.'@customer'.$ti.'.example','status'=>'ACTIVE']);
            $employees=[];for($ei=0;$ei<200;$ei++){$status=$ei<160?'ACTIVE':(['ACTIVE','ACTIVE','ON_LEAVE','DISMISSED'][$ei%4]);$employee=$this->add('employees','employee-'.$ti.'-'.$ei,['tenant_id'=>$tenant,'name'=>$last[$ei%16].' '.$first[(int)floor($ei/16)%16].' '.['Александрович','Сергеевич','Иванович','Михайлович'][$ei%4],'phone'=>'+7920'.str_pad((string)($ti*1000+$ei),7,'0',STR_PAD_LEFT),'email'=>'employee'.$ei.'@'.$slug.'.example','qualification'=>$ei<160?6:4+$ei%3,'badge'=>'СО-'.str_pad((string)($ti*1000+$ei+1),5,'0',STR_PAD_LEFT),'passport'=>'ДЕМО '.str_pad((string)($ei+1),6,'0',STR_PAD_LEFT),'status'=>$status,'hired_at'=>'2024-'.str_pad((string)(1+$ei%12),2,'0',STR_PAD_LEFT).'-15','personal_card'=>'ЛК-2026-'.($ei+1)]);$employees[]=$employee;$this->add('personal_cards','card-'.$ti.'-'.$ei,['tenant_id'=>$tenant,'name'=>'Личная карточка · '.$last[$ei%16],'employee_id'=>$employee,'number'=>'ЛК-2026-'.($ei+1),'issued_at'=>'2025-01-15','authority'=>'Демонстрационный территориальный орган','status'=>$status==='DISMISSED'?'SURRENDERED':'ACTIVE','surrendered_at'=>$status==='DISMISSED'?'2026-09-15':null,'receipt'=>'ДЕМО-ВХ-'.($ei+1)]);
                foreach($types as$di=>$type){$days=match(($ei+$di)%13){0=>-12,1=>7,2=>14,3=>30,4=>1,default=>120+($ei*7)%500};$expiry=$date->modify(($days>=0?'+':'').$days.' days')->format('Y-m-d');$status=($ei+$di)%19===0?'PENDING_REVIEW':($days<0?'EXPIRED':($days<=30?'EXPIRING':'VALID'));$doc=$this->add('documents','doc-'.$ti.'-'.$ei.'-'.$di,['tenant_id'=>$tenant,'name'=>['Удостоверение','Медицинское заключение','Квалификация'][$di].' · '.$last[$ei%16],'employee_id'=>$employee,'type_id'=>$type,'number'=>'ДЕМО-'.$ti.'-'.$ei.'-'.$di,'issued_at'=>'2025-01-15','expires_at'=>$expiry,'status'=>$status,'scan_status'=>'CLEAN','file_path'=>'demo-document.png','mime'=>'image/png','sha256'=>is_file($fixture)?hash_file('sha256',$fixture):null]);if($status!=='PENDING_REVIEW')$this->add('document_reviews','review-'.$ti.'-'.$ei.'-'.$di,['tenant_id'=>$tenant,'name'=>'Проверка документа','document_id'=>$doc,'decision'=>'VALID','reason'=>'Проверено ответственным кадровиком','actor_id'=>$users['hr']]);}
            }
            $facilities=[];$posts=[];$qrs=[];
            for($fi=0;$fi<24;$fi++){
                $customer=$customers[$fi%18];$contract=$this->add('contracts','contract-'.$ti.'-'.$fi,['tenant_id'=>$tenant,'name'=>'Охрана объекта · '.($fi+1),'number'=>'ДО-'.$ti.'-2026-'.str_pad((string)($fi+1),3,'0',STR_PAD_LEFT),'customer_id'=>$customer,'license_id'=>$license,'starts_at'=>'2026-01-01','ends_at'=>'2027-12-31','signed_at'=>'2025-12-20','amount'=>180000+$fi*12000,'services'=>['physical','access'],'status'=>$fi%11===0?'DRAFT':'ACTIVE','ownership_proof'=>'Демонстрационная выписка / право аренды № '.($fi+100),'compensation'=>'Условия ответственности согласованы в договоре','legacy'=>$fi%7===0?1:0,'source_version'=>1,'legal_hold_until'=>'2030-12-31','signage'=>['required'=>true,'placed'=>$fi%5!==0,'note'=>'Физическое размещение выполняет ЧОП/заказчик']]);
                $facility=$this->add('facilities','facility-'.$ti.'-'.$fi,['tenant_id'=>$tenant,'name'=>$objectNames[$fi%12].($fi>=12?' · корпус 2':''),'customer_id'=>$customer,'contract_id'=>$contract,'address'=>$city.', '.['ул. Центральная','просп. Победы','ул. Заводская','ул. Мира','Логистический проезд'][$fi%5].', '.($fi*3+10),'city'=>$city,'lat'=>$lat+($fi%6-3)*0.014,'lng'=>$lng+((int)floor($fi/6)-2)*0.019,'radius'=>100+($fi%5)*30,'timezone'=>'Europe/Moscow','status'=>'ACTIVE','contact_name'=>'Ответственный объекта '.($fi+1),'phone'=>'+7930'.str_pad((string)($ti*100+$fi),7,'0',STR_PAD_LEFT)]);$facilities[]=$facility;
                for($pi=0;$pi<3;$pi++){$index=$fi*3+$pi;$post=$this->add('posts','post-'.$ti.'-'.$index,['tenant_id'=>$tenant,'name'=>['КПП / главный вход','Контроль территории','Внутренний пост'][$pi].' · '.($fi+1),'facility_id'=>$facility,'mode'=>'12/12','qualification'=>4,'headcount'=>1,'status'=>'ACTIVE','instruction'=>'Принимать смену по журналу. Проверять пропуска, фиксировать события. При происшествии уведомить дежурного. Соблюдать регламент объекта.','instruction_version'=>1]);$posts[]=$post;$qrs[]='demo-qr-'.$ti.'-'.$index;
                    $this->add('instructions','instruction-'.$ti.'-'.$index,['tenant_id'=>$tenant,'name'=>'Инструкция поста','post_id'=>$post,'text'=>'Проверка журналов и средств связи; пропускной режим; обход территории каждые два часа; передача дежурства по чек-листу.','revision'=>1,'author_id'=>$users['operations']]);
                    $this->add('qr_points','qr-'.$ti.'-'.$index,['tenant_id'=>$tenant,'name'=>'Контрольная точка · '.$index,'facility_id'=>$facility,'post_id'=>$post,'token'=>$qrs[$index],'status'=>'ACTIVE']);
                    $this->add('shift_templates','template-'.$ti.'-'.$index,['tenant_id'=>$tenant,'name'=>'Дневная смена · '.$index,'post_id'=>$post,'start_time'=>'07:00','duration_hours'=>12,'weekdays'=>[1,2,3,4,5,6,7]]);
                    for($day=-7;$day<=6;$day++)foreach([7,19]as$slot=>$hour){$start=$date->modify(($day>=0?'+':'').$day.' days')->setTime($hour,0);$end=$start->modify('+12 hours');$startUtc=$start->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s');$endUtc=$end->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s');$empty=($index+$day+$slot)%17===0;$shiftKey='shift-'.$ti.'-'.$index.'-'.$day.'-'.$slot;$shift=$this->add('shifts',$shiftKey,['tenant_id'=>$tenant,'name'=>($hour===7?'Дневная':'Ночная').' · '.$start->format('d.m'),'post_id'=>$post,'starts_at'=>$startUtc,'ends_at'=>$endUtc,'published'=>$day<=3?1:0,'status'=>$empty?'UNFILLED':($day<0?'COMPLETED':($day<=3?'PUBLISHED':'DRAFT'))]);
                        if(!$empty){$employee=$employees[$index*2+$slot];$assignment=$this->add('assignments','a-'.$shiftKey,['tenant_id'=>$tenant,'name'=>'Назначение · '.$start->format('d.m H:i'),'shift_id'=>$shift,'employee_id'=>$employee,'status'=>'CONFIRMED','confirmed_at'=>$start->modify('-2 days')->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s')]);
                            if($end->getTimestamp()<time()){foreach(['CHECK_IN'=>$start,'CHECK_OUT'=>$end]as$event=>$moment){$review=($index+$day)%29===0;$this->add('attendance','att-'.$shiftKey.'-'.$event,['tenant_id'=>$tenant,'name'=>$event==='CHECK_IN'?'Заступление':'Завершение','assignment_id'=>$assignment,'employee_id'=>$employee,'event_type'=>$event,'client_time'=>$moment->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s'),'server_time'=>$moment->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s'),'lat'=>$lat+($fi%6-3)*0.014,'lng'=>$lng+((int)floor($fi/6)-2)*0.019,'accuracy'=>$review?150:12,'device_id'=>'demo-device-'.$index,'qr_token'=>$qrs[$index],'offline'=>$index%11===0?1:0,'status'=>$review?'REQUIRES_REVIEW':'VALID','reasons'=>$review?['Недостаточная точность GPS']:[],'idempotency_key'=>'seed-'.$shiftKey.'-'.$event,'duration_minutes'=>$event==='CHECK_OUT'?720:null]);}}
                        }
                    }
                }
                for($ri=0;$ri<4;$ri++)$this->add('compliance_tasks','task-'.$ti.'-'.$fi.'-'.$ri,['tenant_id'=>$tenant,'name'=>$rules[$ri][1].' · ДО-'.$fi,'contract_id'=>$contract,'rule_id'=>$ruleIds[$ri],'rule_version'=>1,'deadline'=>$date->modify(($fi%6-2).' days')->setTime(17,0)->setTimezone(new \DateTimeZone('UTC'))->format('Y-m-d H:i:s'),'status'=>['DUE','CONFIRMED','OVERDUE','MARKED_SENT'][($fi+$ri)%4],'channel'=>'Email / вручную','receipt'=>($fi+$ri)%4===1?'ВХ-'.($fi*4+$ri):null,'attachment'=>'ИСХ-'.($fi*4+$ri),'sent_at'=>Support::now(),'author_id'=>$users['tenant_admin']]);
                $this->add('incidents','incident-'.$ti.'-'.$fi,['tenant_id'=>$tenant,'name'=>['Попытка прохода без пропуска','Сработала пожарная сигнализация','Нарушение режима парковки','Проверка периметра'][$fi%4],'facility_id'=>$facility,'category'=>'SECURITY','severity'=>$fi%5===0?'HIGH':'MEDIUM','status'=>$fi%3===0?'OPEN':'RESOLVED','published'=>$fi%4===0?0:1,'description'=>'Событие зафиксировано дежурной сменой. Выполнены действия по инструкции. Ответственный уведомлён.','internal_note'=>'Внутренние сведения оперативного руководителя']);
                $this->add('patrols','patrol-'.$ti.'-'.$fi,['tenant_id'=>$tenant,'name'=>'Плановый обход территории','facility_id'=>$facility,'status'=>$fi%6===0?'MISSED':'COMPLETED','completed_points'=>$fi%6===0?3:6,'total_points'=>6,'finished_at'=>Support::now()]);
                $this->add('reports','report-'.$ti.'-'.$fi,['tenant_id'=>$tenant,'name'=>'Отчёт об охране · '.$objectNames[$fi%12],'customer_id'=>$customer,'facility_id'=>$facility,'period'=>$date->modify('-1 month')->format('m.Y'),'status'=>$fi%5===0?'DRAFT':'PUBLISHED','published'=>$fi%5===0?0:1,'content'=>'Покрытие постов: 98%. Плановые обходы выполнены. Происшествия обработаны по установленному регламенту. Сводные показатели доступны в кабинете заказчика.','internal_note'=>'Внутренние комментарии по кадровым заменам']);
            }
            for($ei=0;$ei<200;$ei++)$this->db->run('UPDATE cp_employees SET facility_id=? WHERE id=?',[$facilities[(int)floor($ei/6)%24],$employees[$ei]]);
            $this->db->run('UPDATE cp_users SET customer_id=? WHERE id=?',[$customers[0],$users['customer']]);$this->db->run('UPDATE cp_users SET employee_id=?,scopes=? WHERE id=?',[$employees[0],Support::json([$facilities[0]]),$users['guard']]);$this->db->run('UPDATE cp_users SET scopes=? WHERE id=?',[Support::json(array_slice($facilities,0,3)),$users['object_manager']]);
            for($vi=0;$vi<16;$vi++)$this->add('vacancies','vacancy-'.$ti.'-'.$vi,['tenant_id'=>$tenant,'name'=>['Охранник в бизнес-центр','Охранник на складской комплекс','Охранник-контролёр КПП','Старший смены'][$vi%4],'facility_id'=>$facilities[$vi%24],'city'=>$city,'salary_from'=>45000+$vi*2000,'salary_to'=>60000+$vi*2500,'schedule'=>['2/2','Сутки через трое','Вахта 15/15','Дневные смены'][$vi%4],'qualification'=>4+$vi%3,'description'=>'Официальное оформление, своевременные выплаты два раза в месяц, удобный график. Обязанности: контроль доступа, обход территории, ведение журнала. Требуется удостоверение охранника.','status'=>'PUBLISHED','pinned_rank'=>$ti===0&&$vi<3?$vi+1:null,'pinned_at'=>$ti===0&&$vi<3?Support::now():null]);
            for($ni=0;$ni<60;$ni++)$this->add('notifications','notification-'.$ti.'-'.$ni,['tenant_id'=>$tenant,'name'=>['Срок документа истекает','Требуется подтверждение смены','Новая задача по договору','Смена остаётся незакрытой'][$ni%4],'user_id'=>$users['tenant_admin'],'entity_type'=>'employees','entity_id'=>$employees[$ni],'dedupe_key'=>'seed-notification-'.$ni,'status'=>$ni%5===0?'READ':'NEW','payload'=>['text'=>'Проверьте запись и назначьте ответственного.']]);
            $this->add('contract_templates','contract-template-'.$ti,['tenant_id'=>$tenant,'name'=>'Договор физической охраны','text'=>'Организация {{tenant}} оказывает услуги охраны объекта {{facility}} на условиях согласованного договора.','source'=>'Шаблон для демонстрации','revision'=>1,'published'=>1,'published_by'=>$users['tenant_admin']]);
            for($ai=0;$ai<100;$ai++)$this->db->run('INSERT INTO cp_audit(tenant_id,actor_id,action,entity_type,entity_id,metadata,ip,device,correlation_id,created_at)VALUES(?,?,?,?,?,?,?,?,?,?)',[$tenant,$users['operations'],['shift.published','assignment.created','document.reviewed','contract.activated'][$ai%4],['shifts','assignments','documents','contracts'][$ai%4],$facilities[$ai%24],Support::json(['source'=>'demo','old'=>null,'new'=>['status'=>'ACTIVE']]),'127.0.0.1','demo-device',Support::uuid(),gmdate('Y-m-d H:i:s',time()-$ai*1900)]);
        }
    }
}
