<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/src/Core/Autoloader.php';
use Choppro\Stage2\{Config,Db,Access,Resources,Operations,Mobile,Support,Problem,PatrolRoutes,Reporting,Xlsx,Auth,MobileFiles,Backup,Migrator,Seeder};
$config=Config::load();$db=new Db($config);$checks=0;
function check34(bool $v,string $message):void{global$checks;if(!$v)throw new RuntimeException($message);$checks++;}
function problem34(callable $fn,string $code):void{try{$fn();}catch(Problem$e){check34($e->codeName===$code,$code.' expected, '.$e->codeName.' received');return;}throw new RuntimeException($code.' expected');}
$admin=$db->one("SELECT * FROM cp_users WHERE email='admin@obereg.example'");$a=new Access($db,$admin);$r=new Resources($a,$config);$ops=new Operations($r);
$db->pdo->beginTransaction();
try{
 $facility=$a->find('facilities',Seeder::id('facility-0-0'));$employee=$r->create('employees',['name'=>'Сотрудник мобильной проверки','qualification'=>6,'status'=>'ACTIVE','facility_id'=>$facility['id'],'badge'=>'AT-MOBILE']);$shift=$r->create('shifts',['name'=>'Мобильная смена','post_id'=>Seeder::id('post-0-0'),'starts_at'=>gmdate('c',time()-3600),'ends_at'=>gmdate('c',time()+14400)]);$assignment=$ops->assign(['name'=>'Мобильное назначение','shift_id'=>$shift['id'],'employee_id'=>$employee['id']]);$ops->publish($shift['id']);
 $user=$db->one("SELECT * FROM cp_users WHERE email='guard@obereg.example'");$db->run('UPDATE cp_users SET employee_id=? WHERE id=?',[$employee['id'],$user['id']]);$user['employee_id']=$employee['id'];$ga=new Access($db,$user);$gr=new Resources($ga,$config);$mobile=new Mobile($gr);$snapshot=$mobile->snapshot();check34(in_array($assignment['id'],array_column($snapshot['assignments'],'id'),true),'Published own assignment visible');check34($snapshot['policy']!==null,'Published policy delivered');problem34(fn()=>(new Mobile($r))->snapshot(),'GUARD_ONLY');problem34(fn()=>$ga->find('facilities',Seeder::id('facility-1-0')),'NOT_FOUND');
 $clock=time()-600;$event=fn($type,$payload,$key=null,$timestamp=null)=>['id'=>$key??Support::uuid(),'type'=>$type,'payload'=>$payload,'device_id'=>'mobile-test-device','client_time'=>gmdate('c',$timestamp??$clock)];
 problem34(fn()=>$mobile->event($event('ASSIGNMENT_CONFIRM',['assignment_id'=>$assignment['id'],'accept'=>true])),'POLICY_ACK_REQUIRED');
 $policy=$event('POLICY_ACK',['policy_id'=>$snapshot['policy']['id']]);$p=$mobile->event($policy);check34($p['ok']===true,'Policy acknowledged');check34($mobile->event($policy)===$p,'Policy retry idempotent');$changed=$policy;$changed['payload']['policy_id']='missing';problem34(fn()=>$mobile->event($changed),'IDEMPOTENCY_CONFLICT');
 $mobile->event($event('ASSIGNMENT_CONFIRM',['assignment_id'=>$assignment['id'],'accept'=>true]));check34($db->scalar('SELECT status FROM cp_assignments WHERE id=?',[$assignment['id']])==='CONFIRMED','Assignment confirmation');
 $gps=['assignment_id'=>$assignment['id'],'lat'=>$facility['lat'],'lng'=>$facility['lng'],'accuracy'=>5,'qr_token'=>'demo-qr-0-0'];problem34(fn()=>$mobile->event($event('CHECK_IN',$gps)),'INSTRUCTION_ACK_REQUIRED');$instruction=$db->one('SELECT * FROM cp_instructions WHERE tenant_id=? AND post_id=? ORDER BY revision DESC LIMIT 1',[$a->tenant(),$shift['post_id']]);$mobile->event($event('INSTRUCTION_ACK',['instruction_id'=>$instruction['id']]));
 $checkin=$event('CHECK_IN',$gps);$saved=$mobile->event($checkin);check34($saved['status']==='VALID','QR and GPS valid');check34($mobile->event($checkin)['id']===$saved['id'],'Attendance replay exact row');check34((int)$db->scalar('SELECT COUNT(*) FROM cp_attendance WHERE id=?',[$saved['id']])===1,'No duplicate attendance');
 $wrong=$event('CHECK_IN',[...$gps,'assignment_id'=>Seeder::id('assignment-1-0-0')]);problem34(fn()=>$mobile->event($wrong),'NOT_FOUND');$future=$event('CHECK_IN',$gps,null,time()+600);problem34(fn()=>$mobile->event($future),'TIME_INVALID');
 $qr=$db->all("SELECT * FROM cp_qr_points WHERE tenant_id=? AND facility_id=? AND status='ACTIVE' ORDER BY created_at,id LIMIT 3",[$a->tenant(),$facility['id']]);$points=array_map(fn($q)=>['name'=>$q['name'],'qr_point_id'=>$q['id'],'lat'=>$facility['lat'],'lng'=>$facility['lng'],'radius'=>100,'offset_minutes'=>0],$qr);$route=(new PatrolRoutes($r))->save(['name'=>'Проверочный маршрут','facility_id'=>$facility['id'],'ordered'=>1,'window_minutes'=>120,'tolerance_minutes'=>15,'status'=>'ACTIVE','points'=>$points]);check34($route['status']==='ACTIVE','Visual builder saves complete route');$routePoints=$db->all('SELECT * FROM cp_patrol_route_points WHERE route_id=? AND deleted_at IS NULL ORDER BY position',[$route['id']]);check34(count($routePoints)===3,'All route points saved');
 $start=$event('PATROL_START',['route_id'=>$route['id'],'assignment_id'=>$assignment['id']]);$run=$mobile->event($start);check34($run['status']==='IN_PROGRESS','Patrol started');check34($mobile->event($start)['id']===$run['id'],'Patrol creation replay');$scan=fn($i,$extra=[])=>['patrol_key'=>$start['id'],'point_id'=>$routePoints[$i]['id'],'qr_token'=>$qr[$i]['token'],'lat'=>$facility['lat'],'lng'=>$facility['lng'],'accuracy'=>5,...$extra];
 problem34(fn()=>$mobile->event($event('CHECKPOINT_SCAN',$scan(1))),'SCAN_EXPLANATION_REQUIRED');$rotated=$qr[0]['token'];$db->run("UPDATE cp_qr_points SET status='INACTIVE' WHERE id=?",[$qr[0]['id']]);problem34(fn()=>$mobile->event($event('CHECKPOINT_SCAN',$scan(0))),'QR_REVOKED');$db->run("UPDATE cp_qr_points SET status='ACTIVE' WHERE id=?",[$qr[0]['id']]);
 foreach([0,1,2]as$i){$value=$event('CHECKPOINT_SCAN',$scan($i));$result=$mobile->event($value);check34($result['status']==='VALID','Ordered checkpoint '.$i);check34($mobile->event($value)['id']===$result['id'],'Checkpoint replay '.$i);}
 $finish=$mobile->event($event('PATROL_FINISH',['patrol_key'=>$start['id']]));check34($finish['status']==='COMPLETED'&&(int)$finish['completed_points']===3,'Complete patrol');problem34(fn()=>$mobile->event($event('CHECKPOINT_SCAN',$scan(0))),'PATROL_FINISHED');
 $revision=(new PatrolRoutes($r))->save([...$route,'name'=>'Измененное название','points'=>array_reverse($points)]);check34($revision['name']==='Измененное название','Route change');check34(Support::decode($db->scalar('SELECT route_snapshot FROM cp_mobile_patrol_runs WHERE patrol_id=?',[$run['id']]))['route']['name']==='Проверочный маршрут','Running route snapshot immutable');problem34(fn()=>(new PatrolRoutes($r))->save([...$route,'points'=>$points]),'VERSION_CONFLICT');
 $incidentEnvelope=$event('INCIDENT_CREATE',['assignment_id'=>$assignment['id'],'name'=>'Повреждено ограждение','description'=>'Выявлено повреждение ограждения у въезда. Доступ временно ограничен.','category'=>'SECURITY','severity'=>'CRITICAL','measures'=>'Место ограждено, ответственному передано по телефону.']);$incident=$mobile->event($incidentEnvelope);check34($incident['published']==0,'Incident private until reviewed');check34($incident['escalation_status']==='NOT_CONNECTED','No external notification falsely sent');check34($mobile->event($incidentEnvelope)['id']===$incident['id'],'Incident replay');check34($ga->find('incidents',$incident['id'])['id']===$incident['id'],'Guard own incident visible');$foreign=$db->one('SELECT id FROM cp_incidents WHERE tenant_id<>? LIMIT 1',[$a->tenant()]);problem34(fn()=>$ga->find('incidents',$foreign['id']),'NOT_FOUND');
 $outEvent=$event('CHECK_OUT',$gps,null,$clock+120);$out=$mobile->event($outEvent);check34($out['status']==='VALID','Checkout valid');check34((int)$db->scalar('SELECT worked_minutes FROM cp_presence WHERE assignment_id=?',[$assignment['id']])===2,'Actual minutes match immutable events');
 $period=['from'=>gmdate('Y-m-d',$clock-86400),'to'=>gmdate('Y-m-d',$clock+86400),'employee_id'=>$employee['id'],'facility_id'=>$facility['id']];$reporter=new Reporting($r);$sheet=$reporter->data('timesheet',$period);check34($sheet['total']===1,'Timesheet employee and facility filter');check34(abs($sheet['summary']['Факт, ч']-.03)<.01,'Timesheet actual hours');check34(count($reporter->data('accounting',$period)['headers'])===9,'Accounting file columns');check34($reporter->data('patrols',$period)['summary']['Обходов']>=1,'Patrols reporting');check34($reporter->data('incidents',$period)['total']>=1,'Incidents reporting');check34($reporter->data('coverage',$period)['summary']['Назначено']>=1,'Coverage report');problem34(fn()=>(new Reporting($gr))->data('timesheet',$period),'FORBIDDEN');problem34(fn()=>$reporter->data('coverage',['from'=>'2020-01-01','to'=>'2026-12-31']),'DATE_RANGE');check34(Reporting::cell('=HYPERLINK("https://example.test")')[0]==="'",'CSV formula blocked');check34(Reporting::cell("\t+1")[0]==="'",'CSV whitespace formula blocked');check34(Reporting::cell(-5)===-5,'Numeric cells preserved');
 $xlsx=Xlsx::render([['Сотрудник','Факт, ч'],['Тест',2.5]],'Проверка');$x=$config['storage'].'/test-export.xlsx';file_put_contents($x,$xlsx);$zip=new ZipArchive();check34($zip->open($x)===true,'XLSX opens as valid OOXML');check34(str_contains($zip->getFromName('xl/worksheets/sheet1.xml'),'Тест'),'Russian Excel contents');check34(!str_contains($zip->getFromName('xl/worksheets/sheet1.xml'),'<f>'),'No embedded spreadsheet formulas');$zip->close();unlink($x);
 $monthly=$reporter->monthly(['facility_id'=>$facility['id'],'period'=>gmdate('Y-m')]);check34($monthly['id']===$reporter->monthly(['facility_id'=>$facility['id'],'period'=>gmdate('Y-m')])['id'],'Monthly request deduplicated');Reporting::work($db,$config);$job=$db->one('SELECT * FROM cp_report_jobs WHERE id=?',[$monthly['id']]);check34($job['status']==='READY','Monthly report generated');$draft=$a->find('reports',$job['report_id']);check34(!(int)$draft['published'],'Generated report not auto published');$r->update('reports',$draft['id'],['version'=>$draft['version'],'published'=>1,'status'=>'PUBLISHED']);check34($db->scalar('SELECT status FROM cp_report_jobs WHERE id=?',[$job['id']])==='PUBLISHED','Monthly publication state');
 $oldCount=$db->scalar('SELECT COUNT(*) FROM cp_mobile_events WHERE user_id=?',[$user['id']]);$bad=$event('INCIDENT_CREATE',['assignment_id'=>$assignment['id'],'name'=>'x','description'=>'x','severity'=>'HIGH','category'=>'SECURITY']);problem34(fn()=>$mobile->event($bad),'INCIDENT_INVALID');check34($db->scalar('SELECT COUNT(*) FROM cp_mobile_events WHERE user_id=?',[$user['id']])===$oldCount,'Failed action writes no successful ledger');
 $noGpsShift=$r->create('shifts',['name'=>'Смена с объяснением','post_id'=>Seeder::id('post-0-0'),'starts_at'=>gmdate('c',time()+20000),'ends_at'=>gmdate('c',time()+24000)]);$noGpsAssignment=$ops->assign(['name'=>'Назначение без GPS','shift_id'=>$noGpsShift['id'],'employee_id'=>$employee['id']]);$ops->publish($noGpsShift['id']);$noGps=$ops->attendance(['assignment_id'=>$noGpsAssignment['id'],'event_type'=>'CHECK_IN','client_time'=>gmdate('c',time()+20000),'no_gps'=>true,'explanation'=>'Датчик координат устройства недоступен','device_id'=>'ci-gps','qr_token'=>'demo-qr-0-0','idempotency_key'=>'ci-gps-review']);check34($noGps['status']==='REQUIRES_REVIEW','Missing GPS reviewed');check34($noGps['lat']===null&&$noGps['lng']===null,'Missing GPS stores no invented coordinates');$mobile->event($event('ATTENDANCE_EXPLAIN',['attendance_id'=>$noGps['id'],'reason'=>'В помещении отсутствует устойчивый сигнал спутников.']));check34((int)$db->scalar('SELECT COUNT(*) FROM cp_attendance_explanations WHERE attendance_id=?',[$noGps['id']])===1,'Immutable explanation appended');check34($ga->find('attendance',$noGps['id'])['status']==='REQUIRES_REVIEW','Explanation does not approve attendance');
}finally{if($db->pdo->inTransaction())$db->pdo->rollBack();}
$connection=new PDO('mysql:host='.$config['database']['host'].';port='.$config['database']['port'],$config['database']['user'],$config['database']['password']);$connection->exec('CREATE DATABASE choppro_backup_test CHARACTER SET utf8mb4');$copyConfig=$config;$copyConfig['database']['name']='choppro_backup_test';$copyConfig['storage']=$config['storage'].'/backup-test';$copyConfig['demo']=false;mkdir($copyConfig['storage'],0700,true);
try{$copy=new Db($copyConfig);(new Migrator($copy,$copyConfig))->apply(false);$seed=new Seeder($copy,$copyConfig);$tenant=$seed->add('tenants','backup-tenant',['name'=>'До изменения','slug'=>'backup-test','inn'=>'0000000000','status'=>'ACTIVE','settings'=>[],'features'=>[]]);$uid=$seed->add('users','backup-user',['tenant_id'=>$tenant,'name'=>'Проверочный пользователь','role'=>'tenant_admin','status'=>'ACTIVE','scopes'=>[]]);$u=$copy->one('SELECT * FROM cp_users WHERE id=?',[$uid]);(new Auth($copy,$copyConfig))->issue($u);$folder=$copyConfig['storage'].'/uploads/'.$tenant;mkdir($folder,0700,true);$file=$folder.'/restore-test.pdf';file_put_contents($file,'%PDF-test-restore');$backup=new Backup($copy,$copyConfig);$made=$backup->create();check34($made['status']==='READY','Encrypted backup completed');$verified=$backup->verify($made['id']);check34($verified['counts']['files']===1,'Backup files verified');$path=$copyConfig['storage'].'/backups/'.$made['id'].'.enc';check34(!str_contains(file_get_contents($path),'До изменения'),'Backup plaintext absent');$copy->run('UPDATE cp_tenants SET name=? WHERE id=?',['После изменения',$tenant]);unlink($file);$restored=$backup->restore($made['id']);check34($restored['restored']===true,'Staged atomic restore completed');check34($copy->scalar('SELECT name FROM cp_tenants WHERE id=?',[$tenant])==='До изменения','Database restored');check34(file_get_contents($file)==='%PDF-test-restore','Private file restored');check34((int)$copy->scalar('SELECT COUNT(*) FROM cp_sessions WHERE revoked_at IS NULL')===0,'Restored sessions revoked');check34((int)$copy->scalar('SELECT @@FOREIGN_KEY_CHECKS')===1,'Restore reenables foreign keys');check34($restored['seconds']<14400,'Restore within four hour target in test dataset');
 $bytes=file_get_contents($path);$bytes[strlen($bytes)-4]=chr(ord($bytes[strlen($bytes)-4])^1);file_put_contents($path,$bytes);problem34(fn()=>$backup->restore($made['id']),'BACKUP_CORRUPTED');check34($copy->scalar('SELECT name FROM cp_tenants WHERE id=?',[$tenant])==='До изменения','Corrupt backup leaves live database intact');$copy->run('UPDATE cp_backup_runs SET sha256=? WHERE id=?',[hash_file('sha256',$path),$made['id']]);problem34(fn()=>$backup->verify($made['id']),'BACKUP_INVALID');check34(!is_file($copyConfig['storage'].'/restore.json'),'No unfinished restore journal');
}finally{$connection->exec('DROP DATABASE choppro_backup_test');}
echo 'PASS '.$checks." mobile, reporting, security and restore checks\n";
