'use strict';
class YandexPointMap {
  constructor(el, options={}) {
    this.el=el;this.lat=Number(options.lat??53.195878);this.lng=Number(options.lng??45.018316);this.center=[this.lng,this.lat];this.zoom=16;this.radius=Number(options.radius??150);this.polygon=Array.isArray(options.polygon)?options.polygon:[];this.editable=!!options.editable;this.mode='point';this.onchange=options.onchange||(()=>{});this.paint();
  }
  project(lng,lat){const e=0.0818191908426;const p=Math.max(-85,Math.min(85,lat))*Math.PI/180;const sin=Math.sin(p);const psi=Math.log(Math.tan(Math.PI/4+p/2)*Math.pow((1-e*sin)/(1+e*sin),e/2));const w=256*2**this.zoom;return[(lng+180)/360*w,(1-psi/Math.PI)/2*w];}
  inverse(x,y){const w=256*2**this.zoom,e=0.0818191908426,psi=Math.PI*(1-2*y/w);let p=2*Math.atan(Math.exp(psi))-Math.PI/2;for(let i=0;i<12;i++){const s=Math.sin(p);p=2*Math.atan(Math.exp(psi)*Math.pow((1+e*s)/(1-e*s),e/2))-Math.PI/2;}return[((x/w*360)%360+360)%360-180,p*180/Math.PI];}
  at(x,y){const rect=this.el.querySelector('.map-canvas').getBoundingClientRect(),c=this.project(...this.center);return this.inverse(c[0]+x-rect.width/2,c[1]+y-rect.height/2);}
  offset(lng,lat){const rect=this.el.querySelector('.map-canvas').getBoundingClientRect(),c=this.project(...this.center),p=this.project(lng,lat);return[p[0]-c[0]+rect.width/2,p[1]-c[1]+rect.height/2];}
  paint(){this.el.innerHTML=`<div class="map-canvas"><iframe title="Яндекс.Карты — расположение объекта" loading="lazy" referrerpolicy="origin" allowfullscreen></iframe><svg class="map-geometry" aria-hidden="true"></svg><div class="map-capture" tabindex="0" role="application" aria-label="${this.editable?'Выберите точку на карте. Перетаскивание перемещает карту.':'Карта объекта. Перетаскивание перемещает карту.'}"></div><div class="map-zoom"><button type="button" data-zoom="1" aria-label="Приблизить карту">+</button><button type="button" data-zoom="-1" aria-label="Отдалить карту">−</button></div><button type="button" class="map-center" aria-label="Вернуться к объекту">⌖</button></div>${this.editable?'<div class="map-tools"><button type="button" data-mode="point" class="active">Точка объекта</button><button type="button" data-mode="polygon">Граница геозоны</button><button type="button" data-clear>Сбросить границу</button><span>Нажмите для выбора · перетаскивайте для перемещения</span></div>':''}<div class="map-caption"><span>Яндекс.Карты · ${this.editable?'точка выбирается на карте':'расположение и геозона'}</span><a target="_blank" rel="noopener" class="map-external">Открыть в Яндекс.Картах ↗</a></div>`;
    this.frame=this.el.querySelector('iframe');this.svg=this.el.querySelector('svg');this.capture=this.el.querySelector('.map-capture');
    this.el.querySelectorAll('[data-zoom]').forEach(b=>b.onclick=()=>{this.zoom=Math.max(3,Math.min(19,this.zoom+Number(b.dataset.zoom)));this.draw(true);});this.el.querySelector('.map-center').onclick=()=>{this.center=[this.lng,this.lat];this.draw(true);};
    this.el.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{this.mode=b.dataset.mode;this.el.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));});this.el.querySelector('[data-clear]')?.addEventListener('click',()=>{this.polygon=[];this.draw();this.emit();});
    this.capture.onpointerdown=e=>{if(e.button!==0)return;this.drag={x:e.clientX,y:e.clientY,center:[...this.center],moved:false};this.capture.setPointerCapture(e.pointerId);};
    this.capture.onpointermove=e=>{if(!this.drag)return;const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;if(Math.abs(dx)+Math.abs(dy)>5)this.drag.moved=true;if(this.drag.moved){this.frame.style.transform=`translate(${dx}px,${dy}px)`;this.svg.style.transform=`translate(${dx}px,${dy}px)`;}};
    this.capture.onpointerup=e=>{if(!this.drag)return;const d=this.drag;this.drag=null;this.frame.style.transform='';this.svg.style.transform='';if(d.moved){const p=this.project(...d.center);this.center=this.inverse(p[0]-(e.clientX-d.x),p[1]-(e.clientY-d.y));this.draw(true);}else if(this.editable){const rect=this.capture.getBoundingClientRect(),p=this.at(e.clientX-rect.left,e.clientY-rect.top);if(this.mode==='polygon')this.polygon.push([Number(p[1].toFixed(7)),Number(p[0].toFixed(7))]);else{this.lat=Number(p[1].toFixed(7));this.lng=Number(p[0].toFixed(7));}this.draw();this.emit();}};
    this.capture.onpointercancel=()=>{this.drag=null;this.frame.style.transform='';this.svg.style.transform='';};
    this.capture.onkeydown=e=>{const delta={ArrowLeft:[-80,0],ArrowRight:[80,0],ArrowUp:[0,-80],ArrowDown:[0,80]}[e.key];if(delta){e.preventDefault();const p=this.project(...this.center);this.center=this.inverse(p[0]+delta[0],p[1]+delta[1]);this.draw(true);}if(e.key==='Enter'&&this.editable){e.preventDefault();this.lng=this.center[0];this.lat=this.center[1];this.draw();this.emit();}};
    this.resize=new ResizeObserver(()=>this.draw());this.resize.observe(this.el.querySelector('.map-canvas'));this.draw(true);
  }
  draw(refresh=false){if(refresh){const ll=this.center.map(v=>v.toFixed(7)).join(',');this.frame.src='https://yandex.ru/map-widget/v1/?'+new URLSearchParams({ll,z:this.zoom,l:'map'});}const rect=this.el.querySelector('.map-canvas').getBoundingClientRect();this.svg.setAttribute('viewBox',`0 0 ${rect.width} ${rect.height}`);this.svg.setAttribute('preserveAspectRatio','none');const p=this.offset(this.lng,this.lat);const metersPerPixel=40075016.6856*Math.cos(this.lat*Math.PI/180)/(256*2**this.zoom);const radius=this.radius/metersPerPixel;
    this.svg.innerHTML=this.polygon.length?`<polygon points="${this.polygon.map(([lat,lng])=>this.offset(lng,lat).join(',')).join(' ')}" fill="#0b9f8833" stroke="#079b88" stroke-width="2"/>${this.polygon.map(([lat,lng])=>{const q=this.offset(lng,lat);return`<circle cx="${q[0]}" cy="${q[1]}" r="4" fill="#079b88" stroke="white" stroke-width="2"/>`;}).join('')}`:`<circle cx="${p[0]}" cy="${p[1]}" r="${radius}" fill="#0b9f8820" stroke="#079b88" stroke-width="2" stroke-dasharray="6 4"/>`;
    this.svg.innerHTML+=`<circle cx="${p[0]}" cy="${p[1]}" r="16" fill="#0a9f9030"/><circle cx="${p[0]}" cy="${p[1]}" r="7" fill="#087f79" stroke="white" stroke-width="3"/>`;
    this.el.querySelector('.map-external').href='https://yandex.ru/maps/?'+new URLSearchParams({ll:`${this.lng},${this.lat}`,z:this.zoom,pt:`${this.lng},${this.lat},pm2rdm`});
  }
  set({lat,lng,radius,polygon}){if(lat!==undefined){this.lat=Number(lat);this.lng=Number(lng);this.center=[this.lng,this.lat];}if(radius!==undefined)this.radius=Number(radius);if(polygon!==undefined)this.polygon=polygon;this.draw(lat!==undefined);this.emit();}
  emit(){this.onchange({lat:this.lat,lng:this.lng,radius:this.radius,polygon:this.polygon});}
  destroy(){this.resize?.disconnect();}
  static fromLink(text){let u;try{u=new URL(text);}catch{return null;}if(!/(^|\.)yandex\.(ru|com)$/.test(u.hostname))return null;const raw=u.searchParams.get('whatshere[point]')||u.searchParams.get('pt')||u.searchParams.get('ll');if(!raw)return null;const parts=raw.split(',').map(Number);if(!Number.isFinite(parts[0])||!Number.isFinite(parts[1])||Math.abs(parts[0])>180||Math.abs(parts[1])>85)return null;return{lat:parts[1],lng:parts[0]};}
}
