import React, { useEffect, useRef } from 'react';
import { AccessibilityInfo, ActivityIndicator, Animated, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import Svg, { Path, Circle, Polyline, Rect } from 'react-native-svg';
export const colors = {ink:'#142938',muted:'#687C88',navy:'#102F43',teal:'#117F7A',pale:'#E9F5F2',bg:'#F3F6F7',line:'#DFE7EB',white:'#FFFFFF',red:'#B73A47',amber:'#9F660E'};
const paths: Record<string,string> = {
  shield:'M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6z',calendar:'M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16',qr:'M3 3h6v6H3z M15 3h6v6h-6z M3 15h6v6H3z M15 15h3v3h3v3h-6z',route:'M6 6h12v6H6v6h12 M3 6h1 M20 18h1',alert:'M12 3 2 21h20z M12 9v5 M12 17v1',sync:'M20 7a8 8 0 0 0-14-2 L3 8 M3 3v5h5 M4 17a8 8 0 0 0 14 2l3-3 M21 21v-5h-5',user:'M4 21v-3a8 8 0 0 1 16 0v3 M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8',map:'M9 3 3 5v16l6-2 6 2 6-2V3l-6 2z M9 3v16 M15 5v16',arrow:'M5 12h14 M13 6l6 6-6 6',back:'M19 12H5 M11 6l-6 6 6 6',check:'M4 12l5 5L20 6',file:'M5 3h9l5 5v13H5z M14 3v6h5 M9 13h6 M9 17h6',camera:'M3 7h5l2-3h4l2 3h5v14H3z M12 17a4 4 0 1 0 0-8 4 4 0 0 0 0 8',mic:'M9 3h6v10H9z M5 10v3a7 7 0 0 0 14 0v-3 M12 20v3 M8 23h8',search:'M10 17a7 7 0 1 0 0-14 7 7 0 0 0 0 14 M15 15l6 6',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7v5l4 2',logout:'M9 3H3v18h6 M8 12h13 M17 8l4 4-4 4',point:'M12 22s8-8 8-13a8 8 0 1 0-16 0c0 5 8 13 8 13 M12 12a3 3 0 1 0 0-6 3 3 0 0 0 0 6'};
export function Icon({name,size=22,color=colors.ink}: {name:string;size?:number;color?:string}) { return <Svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke={color} strokeWidth={1.7} strokeLinecap="round" strokeLinejoin="round"><Path d={paths[name] ?? paths.file}/></Svg>; }
export function Label({children,muted=false}: {children:React.ReactNode;muted?:boolean}) { return <Text style={[s.label,muted && {color:colors.muted}]}>{children}</Text>; }
export function Heading({children,small=false}: {children:React.ReactNode;small?:boolean}) { return <Text style={[s.heading,small && {fontSize:20}]}>{children}</Text>; }
export function Field({label,value,onChange,placeholder='',multiline=false,keyboardType='default',testID,secure=false}: {label:string;value:string;onChange:(value:string)=>void;placeholder?:string;multiline?:boolean;keyboardType?:'default'|'phone-pad'|'number-pad'|'url'|'email-address';testID?:string;secure?:boolean}) { return <View style={s.field}><Text style={s.fieldLabel}>{label}</Text><TextInput accessibilityLabel={label} testID={testID} style={[s.input,multiline && {height:120,textAlignVertical:'top'}]} value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={colors.muted} multiline={multiline} keyboardType={keyboardType} secureTextEntry={secure} autoCapitalize="none" autoCorrect={false}/></View>; }
export function Button({children,onPress,icon,secondary=false,danger=false,disabled=false,loading=false,testID}: {children:React.ReactNode;onPress:()=>void;icon?:string;secondary?:boolean;danger?:boolean;disabled?:boolean;loading?:boolean;testID?:string}) { return <Pressable accessibilityRole="button" testID={testID} disabled={disabled||loading} onPress={onPress} style={({pressed}) => [s.button,secondary && s.secondary,danger && {backgroundColor:colors.red},(disabled||loading) && {opacity:.5},pressed && {opacity:.8,transform:[{scale:.99}]}]}>{loading?<ActivityIndicator color={secondary?colors.teal:colors.white}/>:icon && <Icon name={icon} color={secondary?colors.teal:colors.white} size={20}/>}<Text style={[s.buttonText,secondary && {color:colors.teal}]}>{children}</Text></Pressable>; }
export function Badge({children,tone='teal'}: {children:React.ReactNode;tone?:'teal'|'amber'|'red'|'muted'}) { const c = tone==='red'?colors.red:tone==='amber'?colors.amber:tone==='muted'?colors.muted:colors.teal; return <View style={[s.badge,{backgroundColor:c+'12'}]}><Text style={{fontSize:12,fontWeight:'700',color:c}}>{children}</Text></View>; }
export function Card({children,onPress,accent=false}: {children:React.ReactNode;onPress?:()=>void;accent?:boolean}) { const style = [s.card,accent && {borderLeftWidth:4,borderLeftColor:colors.teal}]; return onPress?<Pressable accessibilityRole="button" onPress={onPress} style={({pressed}) => [...style,pressed && {backgroundColor:colors.pale}]}>{children}</Pressable>:<View style={style}>{children}</View>; }
export function Empty({title,text,icon='calendar'}: {title:string;text:string;icon?:string}) { return <View style={s.empty}><View style={s.emptyIcon}><Icon name={icon} size={32} color={colors.teal}/></View><Heading small>{title}</Heading><Label muted>{text}</Label></View>; }
export function Fade({children}: {children:React.ReactNode}) { const opacity = useRef(new Animated.Value(1)).current; useEffect(() => { void AccessibilityInfo.isReduceMotionEnabled().then(reduced => { if (!reduced) { opacity.setValue(0); Animated.timing(opacity,{toValue:1,duration:180,useNativeDriver:true}).start(); } }); },[]); return <Animated.View style={{opacity}}>{children}</Animated.View>; }
export function Progress({value,total}: {value:number;total:number}) { const ratio = total?Math.max(0,Math.min(1,value/total)):0; return <View><View style={s.progress}><View style={{width:`${ratio*100}%`,backgroundColor:colors.teal,height:7,borderRadius:7}}/></View><Text style={s.caption}>{value} из {total} контрольных точек</Text></View>; }
export const s = StyleSheet.create({label:{fontSize:15,lineHeight:23,color:colors.ink},heading:{fontSize:27,fontWeight:'800',color:colors.ink,marginBottom:10},field:{marginBottom:15},fieldLabel:{color:colors.ink,fontSize:14,fontWeight:'600',marginBottom:7},input:{height:50,borderWidth:1,borderColor:colors.line,borderRadius:13,paddingHorizontal:14,paddingVertical:12,fontSize:16,color:colors.ink,backgroundColor:colors.white},button:{minHeight:49,borderRadius:13,backgroundColor:colors.teal,paddingHorizontal:17,paddingVertical:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,marginVertical:5},secondary:{backgroundColor:colors.pale,borderColor:'#BDDAD5',borderWidth:1},buttonText:{fontSize:15,fontWeight:'700',color:colors.white},card:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:19,padding:19,marginBottom:14,gap:9},badge:{paddingHorizontal:10,paddingVertical:5,borderRadius:8,alignSelf:'flex-start'},empty:{alignItems:'center',paddingVertical:36,paddingHorizontal:20,gap:10},emptyIcon:{width:62,height:62,backgroundColor:colors.pale,borderRadius:19,alignItems:'center',justifyContent:'center',marginBottom:5},progress:{height:7,borderRadius:7,backgroundColor:colors.line,overflow:'hidden',marginVertical:10},caption:{color:colors.muted,fontSize:13,lineHeight:20},row:{flexDirection:'row',alignItems:'center',gap:12},between:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},section:{fontSize:12,fontWeight:'700',color:colors.muted,letterSpacing:1.2,marginTop:22,marginBottom:12},error:{padding:14,borderRadius:12,backgroundColor:'#FDECEF',marginBottom:12},errorText:{color:colors.red,fontSize:14,lineHeight:21}});
