<?php
declare(strict_types=1);
if(!defined('CHOPPRO_HOST_ROOT'))require __DIR__.'/../host-loader/boot.php';
require_once __DIR__.'/app/HostUpdate.php';
$sessionDir=CHOPPRO_STORAGE_ROOT.'/owner-sessions';if(!is_dir($sessionDir))mkdir($sessionDir,0700,true);session_save_path($sessionDir);session_name('choppro_owner');session_set_cookie_params(['path'=>(CHOPPRO_HOST_BASE?:'').'/','httponly'=>true,'secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','samesite'=>'Strict']);ini_set('session.use_strict_mode','1');session_start();$_SESSION['csrf']??=bin2hex(random_bytes(32));$message='';$error='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 try{
  if(!hash_equals($_SESSION['csrf'],$_POST['csrf']??''))throw new RuntimeException('Обновите страницу и повторите действие');$origin=$_SERVER['HTTP_ORIGIN']??'';if($origin&&parse_url($origin,PHP_URL_HOST)!==preg_replace('/:\d+$/','',$_SERVER['HTTP_HOST']??''))throw new RuntimeException('Действие доступно только с этого портала');
  $action=$_POST['action']??'';if(!in_array($action,['update','database','sync','worker'],true))throw new RuntimeException('Выберите действие');
  if(in_array($action,['update','database','sync'],true)){$sync=$loader->sync(true);if(!empty($sync['error']))throw new RuntimeException($sync['error']);if(!empty($sync['pending']))$message=$sync['pending'];$update=HostUpdate::ensure(true);if(($update['status']??'')!=='ready')throw new RuntimeException($update['message']??'База уже обновляется');$message=($message?$message.' ':'').'БД актуализирована. Существующие данные сохранены. Версия схемы: '.$update['database']['version'].'. Портал и демо используют подготовленную версию.';}
  else{$release=$loader->current('demo');require_once $release['path'].'/backend/src/Core/Autoloader.php';$config=\Choppro\Stage2\Config::load();$result=(new \Choppro\Stage2\Worker(new \Choppro\Stage2\Db($config),$config))->tick();$message='Обработка завершена. Сроки, присутствие и хранение данных проверены.';}
 }catch(Throwable $e){$error=$e instanceof PDOException?'Не удалось завершить обновление БД. Текущая версия продолжает работать.':$e->getMessage();}
}else HostUpdate::ensure();
$state=$loader->state();$schema=$loader->json(CHOPPRO_STORAGE_ROOT.'/schema.json');$update=$loader->json(CHOPPRO_STORAGE_ROOT.'/update.json');$e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$asset=fn($name)=>CHOPPRO_HOST_BASE.'/asset.php?path=acceptance-portal/assets/'.$name.'&release='.$state['portal'];
header('Content-Type: text/html; charset=utf-8');header('Cache-Control: no-store');header('X-Frame-Options: DENY');header('X-Content-Type-Options: nosniff');header("Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'");
?>
<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Управление обновлениями · ЧОППРО</title><link rel="icon" href="<?=$e($asset('favicon.png'))?>"><link rel="stylesheet" href="<?=$e($asset('style.css'))?>"></head><body class="control-body"><main class="control-main"><a class="control-back" href="<?=CHOPPRO_HOST_BASE?>/">← Портал проекта</a><div class="control-title"><img src="<?=$e($asset('brand.png'))?>" alt="Логотип ЧОППРО"><div><p class="eyebrow">РАБОЧАЯ ВЕРСИЯ</p><h1><?=($update['status']??'')==='ready'?'Всё готово к работе':'Управление обновлениями'?></h1><p>Файлы и база обновляются вместе. Дополнительный вход не требуется.</p></div></div>
<?php if($message):?><div class="notice success" role="status"><?=$e($message)?></div><?php endif?><?php if($error):?><div class="warning" role="alert"><?=$e($error)?></div><?php endif?>
<section class="control-card" id="database"><div class="control-state"><span class="state-orb">↻</span><div><h2>Обновление системы</h2><p>Новая версия сначала проверяется, затем применяются изменения базы. Ваши записи сохраняются.</p></div><span class="badge">Схема <?=$e($schema['version']??0)?></span></div><div class="toolbar"><?php foreach(['update'=>'Обновить систему','database'=>'Актуализировать БД','worker'=>'Запустить обработку']as$action=>$label):?><form method="post"><input type="hidden" name="csrf" value="<?=$e($_SESSION['csrf'])?>"><input type="hidden" name="action" value="<?=$action?>"><button class="btn <?=$action==='update'?'primary':''?>"><?=$label?></button></form><?php endforeach?></div><p class="small muted">Портал: <?=$e(substr($state['portal']??'',0,10))?> · Демо: <?=$e(substr($state['demo']??'',0,10))?> · Источник: main</p><?php if(($update['status']??'')==='retry'):?><div class="warning"><?=$e($update['message'])?></div><?php endif?></section>
<section class="control-card"><h2>Открыть рабочее пространство</h2><div class="demo-grid"><?php foreach(['admin'=>['Администратор','Команда, объекты и смены'],'client'=>['Заказчик','Покрытие постов и отчёты'],'platform'=>['Платформа','Организации, лимиты и аудит'],'jobs'=>['Биржа труда','Вакансии и отклики']]as$app=>$d):?><a class="demo-tile" href="<?=CHOPPRO_HOST_BASE?>/demo.php?app=<?=$app?>" target="_blank" rel="noopener"><strong><?=$d[0]?> ↗</strong><span><?=$d[1]?></span></a><?php endforeach?></div></section></main></body></html>
