'use strict';
const fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PORTAL_PLAYWRIGHT_PATH||'playwright');
const assert=(v,m)=>{if(!v)throw Error(m);};
(async()=>{const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1020}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const shots=process.env.PORTAL_SCREENSHOTS||'dist/stage2-screenshots';fs.mkdirSync(shots,{recursive:true});
try{
 await page.goto('http://127.0.0.1:8092/');await page.getByText('Рабочее демо · Этап 2',{exact:true}).waitFor();assert(await page.locator('a[target=_blank][href*="demo.php"]').count()>=4,'Four standalone demos');await page.screenshot({path:path.join(shots,'portal.png'),fullPage:true});
 for(const url of ['/.private/site.php','/.private/current.json','/.loader/boot.php','/INSTALL.txt']){const r=await context.request.get('http://127.0.0.1:8092'+url);assert(r.status()===403,'Private file blocked '+url);}
 await page.goto('http://127.0.0.1:8092/control.php');await page.getByLabel('Пароль управления').fill('CiOwner2026!');await page.getByRole('button',{name:'Войти',exact:true}).click();await page.getByRole('button',{name:'Актуализировать БД',exact:true}).click();await page.getByText('БД актуализирована.',{exact:false}).waitFor();assert((await page.textContent('body')).includes('Существующие данные сохранены'),'DB re-run preserves data');
 const login=async(app)=>{await page.goto('http://127.0.0.1:8092/demo.php?app='+app);await page.getByRole('button',{name:'Войти в систему'}).click();if(app!=='client')await page.getByRole('button',{name:'Подтвердить вход'}).click();await page.locator('.sidebar').waitFor();};
 await login('admin');await page.getByRole('heading',{name:'Рабочий обзор'}).waitFor();await page.screenshot({path:path.join(shots,'admin-dashboard.png'),fullPage:true});
 await page.locator('button.nav-link[data-nav=employees]').click();await page.locator('tr[data-record]').first().waitFor();assert((await page.textContent('body')).includes('200 записей'),'Admin employee list');await page.getByRole('button',{name:'Добавить',exact:true}).click();await page.locator('dialog input[name=name]').fill('Приёмка: сотрудник');await page.locator('dialog input[name=qualification]').fill('6');await page.locator('dialog button.primary').click();await page.getByText('Изменения сохранены',{exact:true}).waitFor();await page.getByPlaceholder('Поиск по названию, номеру, телефону…').fill('Приёмка: сотрудник');await page.getByRole('button',{name:'Найти',exact:true}).click();await page.locator('tr[data-record]').first().waitFor();await page.getByText('Приёмка: сотрудник',{exact:true}).click();await page.getByRole('button',{name:'Редактировать',exact:true}).click();await page.locator('dialog input[name=name]').fill('Приёмка: изменение');await page.locator('dialog button.primary').click();await page.locator('dialog').waitFor({state:'hidden'});
 await page.locator('button.nav-link[data-nav=vacancies]').click();await page.locator('tr[data-record]').filter({hasNotText:'Закреп №'}).first().click();await page.getByRole('button',{name:'Ручной закреп',exact:true}).click();await page.locator('dialog select[name=rank]').selectOption('1');await page.getByRole('button',{name:'Сохранить закреп'}).click();await page.getByText('Закреп обновлён',{exact:true}).waitFor();await page.screenshot({path:path.join(shots,'manual-pin.png'),fullPage:true});
 await page.locator('button.nav-link[data-nav=documents]').click();await page.locator('tr[data-record]').first().waitFor();await page.screenshot({path:path.join(shots,'documents.png'),fullPage:true});
 const adminApi=async(p,method='GET',data={})=>page.evaluate(async({p,method,data})=>{const csrf=(await(await fetch('/demo-api.php?space=admin&path=/v1/csrf')).json()).csrf;const r=await fetch('/demo-api.php?space=admin&path=/v1/'+p,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},...(method==='GET'?{}:{body:JSON.stringify(data)})});return {status:r.status,data:await r.json()};},{p,method,data});
 for(const key of ['customers','contracts','licenses','compliance_tasks','facilities','posts','shifts','assignments','attendance','users','roles','personal_cards']){const r=await adminApi(key);assert(r.status===200,'API list '+key+JSON.stringify(r.data));}
 const users=(await adminApi('users')).data.items,guard=users.find(u=>u.role==='guard');const docs=(await adminApi('documents')).data.items;const request=await context.request.post('http://127.0.0.1:8092/demo-api.php?space=admin&path=/v1/employees',{data:{name:'CSRF test',qualification:6}});assert(request.status()===403,'CSRF required');
 await login('client');await page.screenshot({path:path.join(shots,'client-dashboard.png'),fullPage:true});await page.locator('button.nav-link[data-nav=facilities]').click();await page.locator('.facility-card').first().waitFor();assert(await page.locator('.facility-card').count()===2,'Client only own facilities');await page.locator('button.nav-link[data-nav=reports]').click();await page.locator('tr[data-record]').first().waitFor();await page.locator('tr[data-record]').first().click();await page.getByRole('button',{name:'Ознакомлен с отчётом'}).click();await page.getByText('Действие выполнено',{exact:true}).waitFor();const reports=await(await context.request.get('http://127.0.0.1:8092/demo-api.php?space=client&path=/v1/reports')).json();const pdf=await context.request.get('http://127.0.0.1:8092/demo-api.php?space=client&path=/v1/reports/'+reports.items[0].id+'/pdf');assert(pdf.status()===200&&(await pdf.body()).subarray(0,5).toString()==='%PDF-','Client PDF export');const forbidden=await context.request.get('http://127.0.0.1:8092/demo-api.php?space=client&path=/v1/employees');assert(forbidden.status()===403,'Client cannot read HR');
 await login('platform');await page.screenshot({path:path.join(shots,'platform.png'),fullPage:true});await page.locator('button.nav-link[data-nav=tenants]').click();await page.waitForFunction(()=>document.querySelectorAll('tr[data-record]').length===5);assert(await page.locator('tr[data-record]').count()===5,'Five tenants');await page.locator('button.nav-link[data-nav=health]').click();await page.getByRole('button',{name:'Запустить обработчик'}).click();await page.getByText('Обработка завершена.',{exact:false}).waitFor();
 await page.goto('http://127.0.0.1:8092/demo.php?app=jobs');await page.locator('.job-card').first().waitFor();assert(await page.locator('.job-card').count()===80,'80 published jobs');assert(await page.locator('.job-card.pinned').count()===3,'Three pinned jobs');await page.screenshot({path:path.join(shots,'jobs.png'),fullPage:true});await page.locator('button[data-apply]').first().click();await page.locator('dialog input[name=name]').fill('Приёмка: кандидат');await page.locator('dialog input[name=phone]').fill('+79999999999');await page.locator('dialog button.primary').click();await page.getByText('Отклик сохранён',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:8092/demo.php?app=admin');await page.getByRole('heading',{name:'Рабочий обзор',exact:true}).waitFor();await page.locator('.metrics .metric').first().waitFor();await page.screenshot({path:path.join(shots,'mobile-admin.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Mobile no horizontal overflow');
 assert(errors.length===0,'Browser errors: '+errors.join('\n'));console.log('PASS hosting, owner migrations, four applications, CRUD, pin, client isolation, CSRF, report acknowledgement, jobs and responsive UI');
}catch(e){await page.screenshot({path:path.join(shots,'failure.png'),fullPage:true});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
