'use strict';
const fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PORTAL_PLAYWRIGHT_PATH||'playwright');
const assert=(v,m)=>{if(!v)throw Error(m);};
(async()=>{
 const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1020}}),page=await context.newPage(),errors=[],shots=process.env.PORTAL_SCREENSHOTS||'dist/stage2-screenshots',origin='http://127.0.0.1:8092';fs.mkdirSync(shots,{recursive:true});page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().includes('yandex.ru/map-widget'))console.log('Yandex widget:',r.status());});
 const shot=async n=>{console.log('Screen:',n);return page.screenshot({path:path.join(shots,n+'.png'),fullPage:!n.startsWith('mobile')&&!['jobs','documents','map-editor','employee-profile','failure'].includes(n),animations:'disabled',timeout:15000});};
 const api=async(p,method='GET',data={},space='admin',tenant='')=>page.evaluate(async({p,method,data,space,tenant})=>{const csrf=(await(await fetch('/demo-api.php?space='+space+'&path=/v1/csrf')).json()).csrf;const r=await fetch('/demo-api.php?space='+space+'&path=/v1/'+p+(tenant?'&tenant='+tenant:''),{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},...(method==='GET'?{}:{body:JSON.stringify(data)})});return{status:r.status,data:await r.json()};},{p,method,data,space,tenant});
 const login=async app=>{await page.goto(origin+'/demo.php?app='+app);await page.getByRole('button',{name:'Войти в систему'}).click();if(app!=='client')await page.getByRole('button',{name:'Подтвердить вход'}).click();await page.locator('.sidebar').waitFor();};
 try{
  await page.goto(origin+'/');await page.getByText('Рабочее демо · Этап 2',{exact:true}).waitFor();assert(await page.locator('a[target=_blank][href*="demo.php"]').count()>=4,'Four standalone demos');await shot('portal');
  for(const url of ['/.private/site.php','/.private/current.json','/.loader/boot.php'])assert((await context.request.get(origin+url)).status()===403,'Private file '+url);
  await page.goto(origin+'/control.php');assert(await page.locator('input[type=password]').count()===0,'Password removed');await page.getByRole('button',{name:'Актуализировать БД',exact:true}).click();await page.getByText('БД актуализирована.',{exact:false}).waitFor();assert((await page.textContent('body')).includes('Существующие данные сохранены'),'DB preserves data');await shot('control');
  await page.goto(origin+'/?page=openapi');await page.locator('.api-endpoint').first().waitFor();await page.locator('.api-endpoint summary').first().click();await shot('openapi');const color=await page.locator('.api-endpoint code').first().evaluate(e=>getComputedStyle(e).color);assert(color!=='rgb(255, 255, 255)','OpenAPI readable');
  await login('admin');await page.getByRole('heading',{name:'Рабочий обзор',exact:true}).waitFor();await page.locator('.donut svg').first().waitFor();await shot('admin-dashboard');
  await page.locator('[data-nav=employees]').click();await page.locator('[data-view=table]').click();await page.locator('tr[data-record]').first().waitFor();await page.getByRole('button',{name:'Добавить',exact:true}).click();await page.locator('dialog input[name=name]').fill('Приёмка: сотрудник');await page.locator('dialog input[name=qualification]').fill('6');await page.locator('dialog button.primary').click();await page.getByText('Изменения сохранены',{exact:true}).waitFor();await page.getByPlaceholder('Поиск по названию, номеру, телефону…').fill('Приёмка: сотрудник');await page.getByRole('button',{name:'Найти',exact:true}).click();await page.locator('tr[data-record]').first().waitFor();await page.getByText('Приёмка: сотрудник',{exact:true}).click();await page.locator('.profile-hero').waitFor();await shot('employee-profile');await page.getByRole('button',{name:'Редактировать',exact:true}).click();await page.locator('dialog input[name=name]').fill('Приёмка: сотрудник, изменение');await page.locator('dialog button.primary').click();await page.locator('dialog').waitFor({state:'hidden'});await page.locator('[data-view=cards]').click();await page.locator('.entity-card').first().waitFor();await shot('employees-cards');
  await page.locator('[data-nav=facilities]').click();await page.locator('.facility-card').first().waitFor();await shot('facilities');await page.locator('#create').click();await page.locator('dialog input[name=name]').fill('Приёмка: объект на карте');await page.locator('dialog input[name=address]').fill('Пенза, территория склада');await page.locator('dialog input[name=city]').fill('Пенза');const customer=await page.locator('dialog select[name=customer_id] option').evaluateAll(options=>options.find(o=>o.value)?.value);await page.locator('dialog select[name=customer_id]').selectOption(customer);const selected=await page.locator('dialog input[name=lat]').inputValue();const map=page.locator('dialog .map-capture');await map.click({position:{x:220,y:155}});assert((await page.locator('dialog input[name=lat]').inputValue())!==selected,'Click sets location');assert((await page.locator('dialog iframe').getAttribute('src')).startsWith('https://yandex.ru/map-widget/v1/'),'Real Yandex widget');await page.locator('dialog [data-mode=polygon]').click();for(const point of [{x:230,y:180},{x:275,y:190},{x:260,y:235}])await map.click({position:point});assert(JSON.parse(await page.locator('dialog input[name=polygon]').inputValue()).length===3,'Polygon selected on map');const geometry=await page.locator('dialog .map-geometry circle').last().boundingBox();const bounds=await page.locator('dialog .map-canvas').boundingBox();assert(geometry.width>8&&geometry.x>=bounds.x&&geometry.x<bounds.x+bounds.width,'Marker visibly inside map');await page.waitForTimeout(1500);await shot('map-editor');await page.getByRole('button',{name:'Создать объект',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});
  const objects=(await page.evaluate(async()=>{const r=await fetch('/demo-api.php?space=admin&path=/v1/facilities&q='+encodeURIComponent('Приёмка: объект на карте'));return r.json();})).items;assert(objects.length===1&&objects[0].polygon.length===3,'Geometry saved to MySQL');
  await page.locator('[data-nav=attendance]').click();await page.getByRole('heading',{name:'Присутствие на постах',exact:true}).waitFor();const presenceBefore=(await api('presence')).data.summary;await page.locator('#register-attendance').click();await page.locator('#presence-form').waitFor();const presenceAssignment=await page.locator('dialog select[name=assignment_id]').inputValue();await page.locator('#demo-point').click();await page.getByRole('button',{name:'Сохранить отметку',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});assert((await api('presence')).data.summary.present===presenceBefore.present+1,'Presence check-in through UI');await shot('presence');await page.locator('#register-attendance').click();await page.locator('dialog select[name=assignment_id]').selectOption(presenceAssignment);await page.locator('dialog select[name=event_type]').selectOption('CHECK_OUT');await page.locator('#demo-point').click();await page.getByRole('button',{name:'Сохранить отметку',exact:true}).click();await page.locator('dialog').waitFor({state:'hidden'});assert((await api('presence')).data.summary.completed===presenceBefore.completed+1,'Presence check-out through UI');await page.locator('[data-nav=contracts]').click();await page.locator('.entity-card').first().waitFor();await shot('contracts-cards');await page.locator('[data-nav=compliance_tasks]').click();await page.locator('.kanban').waitFor();await shot('task-board');
  await page.locator('[data-nav=vacancies]').click();await page.locator('[data-view=table]').click();await page.locator('tr[data-record]').filter({hasNotText:'Закреп №'}).first().click();await page.getByRole('button',{name:'Ручной закреп',exact:true}).click();await page.locator('dialog select[name=rank]').selectOption('1');await page.getByRole('button',{name:'Сохранить закреп'}).click();await page.getByText('Закреп обновлён',{exact:true}).waitFor();await shot('manual-pin');
  await page.locator('[data-nav=documents]').click();await page.locator('tr[data-record]').first().waitFor();await shot('documents');for(const key of ['customers','contracts','licenses','compliance_tasks','posts','shifts','assignments','attendance','users','roles','personal_cards','analytics'])assert((await api(key)).status===200,'API '+key);
  const request=await context.request.post(origin+'/demo-api.php?space=admin&path=/v1/employees',{data:{name:'CSRF test',qualification:6}});assert(request.status()===403,'CSRF required');await page.locator('[data-nav=audit]').click();await page.locator('.audit-event').first().waitFor();await page.locator('.audit-event').first().click();await shot('audit-details');await page.getByRole('button',{name:'Закрыть',exact:true}).click();await page.locator('[data-nav=retention]').click();await page.getByRole('heading',{name:'Хранение данных',exact:true}).waitFor();await shot('retention');
  await login('client');await page.getByRole('heading',{name:'Ваши объекты сегодня',exact:true}).waitFor();await shot('client-dashboard');await page.locator('[data-nav=facilities]').click();await page.locator('.facility-card').first().waitFor();assert(await page.locator('.facility-card').count()===2,'Client own facilities');await page.locator('[data-nav=reports]').click();await page.locator('[data-view=table]').click();await page.locator('tr[data-record]').first().waitFor();await page.locator('tr[data-record]').first().click();await page.getByRole('button',{name:'Ознакомлен с отчётом'}).click();await page.getByText('Действие выполнено',{exact:true}).waitFor();const reports=(await api('reports','GET',{},'client')).data;const pdf=await context.request.get(origin+'/demo-api.php?space=client&path=/v1/reports/'+reports.items[0].id+'/pdf');assert(pdf.status()===200&&(await pdf.body()).subarray(0,5).toString()==='%PDF-','Client PDF');assert((await api('employees','GET',{},'client')).status===403,'HR hidden from client');
  await login('platform');await page.getByRole('heading',{name:'Платформа под контролем',exact:true}).waitFor();await shot('platform');await page.locator('[data-nav=tenants]').click();await page.waitForFunction(()=>document.querySelectorAll('.tenant-detail-card').length===5);await shot('tenants');await page.locator('[data-settings]').first().click();await page.locator('#limits-form').waitFor();await shot('tenant-limits');await page.getByRole('button',{name:'Закрыть',exact:true}).click();await page.locator('[data-nav=audit]').click();await page.locator('.audit-event').first().waitFor();await shot('platform-audit');await page.locator('[data-nav=health]').click();assert((await api('health/platform','GET',{},'platform')).data.worker?.last_run,'Internal maintenance starts automatically');await page.getByRole('button',{name:'Запустить обработчик'}).click();await page.getByText('Обработка завершена.',{exact:false}).waitFor();await shot('platform-health');
  const tenants=(await api('tenants','GET',{},'platform')).data.items;const t=tenants[0].id;assert((await api('employees','GET',{},'platform',t)).data.code==='SUPPORT_ACCESS_REQUIRED','Support gate');assert((await api('support/access','POST',{reason:'Браузерная проверка доступа поддержки',minutes:1},'platform',t)).status===200,'Support opened');assert((await api('employees','GET',{},'platform',t)).status===200,'Support data permitted');await api('support/close','POST',{},'platform',t);assert((await api('employees','GET',{},'platform',t)).status===403,'Support closed');
  await page.goto(origin+'/demo.php?app=jobs');await page.locator('.job-card').first().waitFor();assert(await page.locator('.job-card').count()===80,'80 jobs');assert(await page.locator('.job-card.pinned').count()===3,'Three pins');await shot('jobs');await page.locator('[data-apply]').first().click();await page.locator('dialog input[name=name]').fill('Приёмка: кандидат');await page.locator('dialog input[name=phone]').fill('+79999999999');await page.locator('dialog button.primary').click();await page.getByRole('heading',{name:'Отклик сохранён',exact:true}).waitFor();await page.getByRole('button',{name:'Вернуться к вакансиям'}).click();
  await page.setViewportSize({width:390,height:844});await page.goto(origin+'/demo.php?app=jobs');await page.locator('.job-card').first().waitFor();await shot('mobile-jobs');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Mobile jobs aligned');await page.goto(origin+'/demo.php?app=admin');await page.getByRole('heading',{name:'Рабочий обзор',exact:true}).waitFor();await shot('mobile-admin');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Mobile admin aligned');assert(errors.length===0,'Browser errors: '+errors.join('\n'));console.log('PASS passwordless control, auto migrations, map polygon, profile/cards, audit, support, four apps, pin, CSRF, report, jobs and responsive UX');
 }catch(e){console.error('Browser step:',page.url());console.error('Page errors:',errors);await shot('failure').catch(x=>console.error('Screenshot:',x.message));throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
