'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium}=require(process.env.PORTAL_PLAYWRIGHT_PATH||'playwright');
const origin='http://127.0.0.1:8092',shots=process.env.PORTAL_SCREENSHOTS||'dist/stage2-screenshots';
const assert=(value,message)=>{if(!value)throw new Error(message);};
const item=value=>value.item||value;
(async()=>{
 const browser=await chromium.launch({headless:true}),admin=await browser.newContext({viewport:{width:1440,height:1020}}),client=await browser.newContext(),mobile=await browser.newContext({viewport:{width:390,height:844}}),page=await mobile.newPage(),control=await admin.newPage(),errors=[],mobileResponses=[],browserConsole=[];fs.mkdirSync(shots,{recursive:true});
 page.on('console',message=>{if(message.type()==='error')browserConsole.push(message.text());});
 page.on('response',async response=>{if(new URL(response.url()).searchParams.get('path')==='/v1/mobile/events'){try{const event=response.request().postDataJSON();mobileResponses.push({type:event.type,point:event.payload?.point_id,patrol:event.payload?.patrol_key,status:response.status(),result:await response.json()});}catch{}}});
 page.on('pageerror',error=>errors.push(error.message));control.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());
 const csrf=async(context,space)=>(await(await context.request.get(origin+'/demo-api.php?space='+space+'&path=/v1/csrf')).json()).csrf;
 const request=async(context,space,p,method='GET',data=null,token=null)=>{const params=new URLSearchParams({space,path:'/v1/'+p});const headers={...(token?{Authorization:'Bearer '+token}:{}),...(method==='GET'?{}:{'X-CSRF-Token':await csrf(context,space)})};const response=await context.request.fetch(origin+'/demo-api.php?'+params,{method,headers,...(data===null?{}:{data})});const body=await response.json();assert(response.ok(),p+': '+response.status()+' '+JSON.stringify(body));return body;};
 const login=async(context,space,email)=>{const first=await request(context,space,'auth/login','POST',{login:email,password:'Demo2026!'});if(first.challenge_id)return request(context,space,'auth/mfa/verify','POST',{challenge_id:first.challenge_id,code:first.demo_code});return first;};
 const picture=fs.readFileSync(path.resolve('mobile/assets/icon.png'));
 let offline=null;
 try{
  await login(admin,'admin','admin@obereg.example');await login(client,'client','customer@obereg.example');
  const facilities=await request(client,'client','facilities');const selected=facilities.items[0];assert(selected,'Client owns a facility');
  const employee=item(await request(admin,'admin','employees','POST',{name:'Проверка мобильных сценариев',qualification:6,status:'ACTIVE',badge:'CI-MOBILE',facility_id:selected.id}));
  const users=await request(admin,'admin','users'),guard=users.items.find(u=>u.email==='guard@obereg.example');assert(guard,'Guard account');await request(admin,'admin','users/'+guard.id,'PUT',{version:guard.version,employee_id:employee.id,scopes:[selected.id]});
  const post=item(await request(admin,'admin','posts','POST',{name:'Пост мобильной проверки',facility_id:selected.id,headcount:1,mode:'Круглосуточно',instruction:'Проверить доступ на объект и передать сведения ответственному. Соблюдать порядок обхода.'}));
  const instructions=await request(admin,'admin','instructions');if(!instructions.items.some(x=>x.post_id===post.id))await request(admin,'admin','instructions','POST',{name:'Инструкция мобильной проверки',post_id:post.id,text:post.instruction,revision:1});
  const shift=item(await request(admin,'admin','shifts','POST',{name:'Мобильная проверка',post_id:post.id,starts_at:new Date(Date.now()-1800000).toISOString(),ends_at:new Date(Date.now()+21600000).toISOString()}));
  const qr=item(await request(admin,'admin','qr_points','POST',{name:'Точка мобильной проверки',facility_id:selected.id,post_id:post.id,status:'ACTIVE'}));
  const qr2=item(await request(admin,'admin','qr_points','POST',{name:'Вторая контрольная точка',facility_id:selected.id,post_id:post.id,status:'ACTIVE'}));
  const route=item(await request(admin,'admin','patrol_routes/save','POST',{name:'Приёмка мобильного маршрута',facility_id:selected.id,ordered:1,status:'ACTIVE',window_minutes:120,tolerance_minutes:15,points:[qr,qr2].map(q=>({name:q.name,qr_point_id:q.id,lat:selected.lat,lng:selected.lng,radius:selected.radius,offset_minutes:0}))}));
  const assignment=item(await request(admin,'admin','assignments','POST',{name:'Мобильная проверка',shift_id:shift.id,employee_id:employee.id}));await request(admin,'admin','shifts/'+shift.id+'/publish','POST',{});
  await page.goto(origin+'/demo.php?app=mobile');await page.getByTestId('server-url').waitFor();await page.getByRole('button',{name:'Демонстрационный сотрудник',exact:true}).click();await page.getByTestId('login-submit').click();await page.getByRole('button',{name:'Подставить код',exact:true}).click();await page.getByTestId('login-submit').click();await page.getByText('Ваш рабочий день',{exact:true}).waitFor();
  assert(await page.locator('.sidebar,.topbar').count()===0,'Mobile demo is an independent workspace');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),'Mobile viewport aligned');await page.waitForTimeout(300);await page.screenshot({path:path.join(shots,'guard-home.png'),animations:'disabled'});
  const token=()=>page.evaluate(()=>JSON.parse(sessionStorage.getItem('choppro.session')).access_token);let guardToken=await token();
  let snapshot=await request(mobile,'mobile','mobile/snapshot','GET',null,guardToken);assert(snapshot.assignments.some(a=>a.id===assignment.id),'Own current assignment delivered');
  if(!snapshot.policy_acknowledged){await page.getByRole('button',{name:'Ознакомьтесь с правилами работы и обработки данных'}).click();await page.getByRole('button',{name:'С правилами ознакомлен',exact:true}).click();}
  await page.getByRole('button',{name:'Главная',exact:true}).first().click();await page.getByRole('button',{name:/Открыть смену/}).click();
  if(await page.getByRole('button',{name:'Подтвердить назначение',exact:true}).count())await page.getByRole('button',{name:'Подтвердить назначение',exact:true}).click();
  if(await page.getByRole('button',{name:'С инструкцией ознакомлен',exact:true}).count())await page.getByRole('button',{name:'С инструкцией ознакомлен',exact:true}).click();
  await page.getByRole('button',{name:'Начать смену',exact:true}).click();await page.getByRole('button',{name:'Использовать тестовую точку объекта',exact:true}).click();await page.getByRole('button',{name:'Сохранить отметку',exact:true}).click();
  await page.getByRole('button',{name:'Завершить смену',exact:true}).waitFor();await page.screenshot({path:path.join(shots,'guard-shift.png'),animations:'disabled'});
  await page.getByRole('tab',{name:'Обходы',exact:true}).click();const routeCard=()=>page.getByText('Приёмка мобильного маршрута',{exact:true}).locator('..');await routeCard().getByRole('button',{name:'Начать обход',exact:true}).click();await routeCard().getByRole('button',{name:'Продолжить обход',exact:true}).click();
  for(let point=0;point<2;point++){await page.getByRole('button',{name:'Отметиться на точке',exact:true}).first().click();await page.getByRole('button',{name:'Использовать тестовую точку объекта',exact:true}).click();await page.getByRole('button',{name:'Сохранить отметку',exact:true}).click();await routeCard().getByRole('button',{name:'Продолжить обход',exact:true}).click();}
  await page.waitForTimeout(300);await page.screenshot({path:path.join(shots,'guard-patrol.png'),animations:'disabled'});await page.getByRole('button',{name:'Завершить обход',exact:true}).click();let completed=null;for(let attempt=0;attempt<20;attempt++){snapshot=await request(mobile,'mobile','mobile/snapshot','GET',null,await token());completed=snapshot.patrols.find(p=>p.route_id===route.id&&p.status==='COMPLETED');if(completed)break;await page.waitForTimeout(500);}assert(completed&&Number(completed.completed_points)===2,'Ordered patrol completed through mobile UI');await page.getByRole('button',{name:'Главная',exact:true}).first().click();await page.getByRole('button',{name:/Открыть смену/}).click();
  offline=async route=>{const u=new URL(route.request().url());if(['/v1/mobile/events','/v1/mobile/upload','/v1/mobile/snapshot'].includes(u.searchParams.get('path')))await route.abort('internetdisconnected');else await route.continue();};await mobile.route('**/demo-api.php?*',offline);
  await page.getByRole('button',{name:'Зафиксировать происшествие',exact:true}).click();await page.getByPlaceholder('Что произошло').fill('Проверка происшествия без связи');await page.getByPlaceholder('Место, обстоятельства и участники').fill('На объекте выявлено повреждение ограждения. Место осмотрено.');await page.getByPlaceholder('Что уже сделано').fill('Выставлен временный пост и ограничен доступ.');await page.getByText('Критическая',{exact:true}).click();
  const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Выбрать файл',exact:true}).click();await(await chooser).setFiles({name:'Материал.png',mimeType:'image/png',buffer:picture});await page.getByText('Материал.png',{exact:true}).waitFor();await page.getByRole('button',{name:'Сохранить происшествие',exact:true}).click();await page.getByText('Журнал отправки',{exact:true}).waitFor();await page.getByText('Вложение происшествия',{exact:true}).waitFor();
  await page.reload();await page.getByText('Ваш рабочий день',{exact:true}).waitFor();await page.getByRole('tab',{name:/^Журнал/}).click();await page.getByText('Вложение происшествия',{exact:true}).waitFor();await page.screenshot({path:path.join(shots,'guard-offline-queue.png'),animations:'disabled'});assert((await page.textContent('body')).includes('Происшествие'),'Incident queue survives reload');
  await mobile.unroute('**/demo-api.php?*',offline);offline=null;
  await page.getByRole('button',{name:'Отправить сохранённое',exact:true}).click();
  let created=null;for(let attempt=0;attempt<30;attempt++){guardToken=await token();snapshot=await request(mobile,'mobile','mobile/snapshot','GET',null,guardToken);created=snapshot.incidents.find(i=>i.name==='Проверка происшествия без связи');if(created?.files.length===1)break;const retries=page.getByRole('button',{name:'Повторить отправку',exact:true});if(await retries.count())await retries.first().click();await page.waitForTimeout(1000);}
  assert(created?.files.length===1,'Incident and encrypted attachment uploaded after reconnect');assert(created.files[0].scan_status==='PENDING_SCAN','No false antivirus approval');
  const file=created.files[0],fileId=file.id;const quarantined=await mobile.request.get(origin+'/demo-api.php?'+new URLSearchParams({space:'mobile',path:'/v1/files/'+fileId+'/link'}),{headers:{Authorization:'Bearer '+guardToken}});assert(quarantined.status()===409,'Quarantine blocks original download');
  const repeated=await mobile.request.post(origin+'/demo-api.php?space=mobile&path=/v1/mobile/upload',{headers:{Authorization:'Bearer '+guardToken,'X-CSRF-Token':await csrf(mobile,'mobile')},multipart:{event_key:crypto.randomUUID(),incident_event_key:created.client_key,file:{name:'Опасный.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\n/JavaScript /JS (alert(1))\n%%EOF')}}});assert(repeated.status()===422,'Active PDF content rejected');
  await control.goto(origin+'/demo.php?app=admin#incidents');await control.locator('.sidebar').waitFor();await control.evaluate(id=>detail('incidents',id),created.id);await control.locator('.incident-workflow').waitFor();await control.screenshot({path:path.join(shots,'incident-workflow.png'),animations:'disabled'});
  await control.getByRole('button',{name:'Материалы происшествия',exact:true}).click();await control.getByRole('button',{name:'Рассмотреть материал',exact:true}).click();await control.locator('textarea[name=reason]').fill('Источник и содержимое материала проверены ответственным сотрудником.');await control.getByRole('button',{name:'Сохранить решение',exact:true}).click();await control.getByRole('button',{name:'Открыть оригинал',exact:false}).waitFor();
  const signed=await request(admin,'admin','files/'+fileId+'/link'),signedParams=new URLSearchParams({space:'admin',path:signed.path,...signed.query}),download=await admin.request.get(origin+'/demo-api.php?'+signedParams);assert(download.ok(),'Authorized signed download');assert((await download.body()).equals(picture),'Uploaded original bytes preserved');
  const hidden=await client.request.get(origin+'/demo-api.php?space=client&path=/v1/incidents/'+created.id+'/files');assert(hidden.status()===404,'Customer cannot see private incident');
  await control.getByRole('button',{name:'Закрыть',exact:true}).click();await control.evaluate(id=>detail('incidents',id),created.id);await control.locator('[data-incident-action]').first().click();await control.locator('select[name=responsible_id]').selectOption({label:'Администратор ЧОО «Оберег»'}).catch(async()=>{const value=await control.locator('select[name=responsible_id] option').evaluateAll(x=>x.find(o=>o.value)?.value);await control.locator('select[name=responsible_id]').selectOption(value);});await control.locator('select[name=status]').selectOption('DONE');await control.locator('textarea[name=result]').fill('Обстоятельства проверены, повреждение устранено и доступ восстановлен.');await control.getByRole('button',{name:'Сохранить действие',exact:true}).click();await control.locator('[data-incident-resolve]').click();await control.locator('textarea[name=result]').fill('Рассмотрение завершено. Угроза объекту устранена.');await control.locator('textarea[name=measures]').fill('Ограждение восстановлено. Контроль доступа усилен.');const responsible=await control.locator('select[name=responsible_id] option').evaluateAll(x=>x.find(o=>o.value)?.value);await control.locator('select[name=responsible_id]').selectOption(responsible);await control.getByRole('button',{name:'Закрыть происшествие',exact:true}).click();await control.getByText('Итог рассмотрения',{exact:true}).waitFor();
  const closed=item(await request(admin,'admin','incidents/'+created.id));assert(closed.status==='RESOLVED','Incident closure through UI');await request(admin,'admin','incidents/'+created.id,'PUT',{version:closed.version,published:1});
  assert((await request(client,'client','incidents/'+created.id+'/files')).items.length===0,'File requires separate publication');await request(admin,'admin','files/'+fileId+'/publish','POST',{published:1});assert((await request(client,'client','incidents/'+created.id+'/files')).items.length===1,'Explicit clean material publication');
  const replay=await client.request.get(origin+'/demo-api.php?'+new URLSearchParams({...Object.fromEntries(signedParams),space:'client'}));assert(replay.status()===403,'Signed link cannot be reused by another session');const publicSummary=await request(client,'client','incidents/'+created.id+'/summary');assert(publicSummary.item===null&&publicSummary.updates.length===0,'Customer does not receive internal measures');
  const ownLink=await request(client,'client','files/'+fileId+'/link'),ownDownload=await client.request.get(origin+'/demo-api.php?'+new URLSearchParams({space:'client',path:ownLink.path,...ownLink.query}));assert(ownDownload.ok()&&(await ownDownload.body()).equals(picture),'Customer can download explicitly published material using own link');
  await control.getByRole('button',{name:'Закрыть',exact:true}).click();await control.locator('[data-nav=settings]').click();await control.locator('#operational-settings').waitFor();assert(await control.locator('#accounting-column-builder [data-column]').count()>=1,'Visual export template');await control.screenshot({path:path.join(shots,'operational-settings.png'),animations:'disabled'});await control.locator('[data-nav=reporting]').click();await control.locator('[data-report-type=timesheet]').click();await control.locator('.report-filters select[name=employee_id]').waitFor();await control.screenshot({path:path.join(shots,'report-center.png'),animations:'disabled'});
  const pdf=await admin.request.get(origin+'/demo-api.php?space=admin&path=/v1/incidents/'+created.id+'/pdf');assert(pdf.ok()&&(await pdf.body()).subarray(0,5).toString()==='%PDF-','Actual incident PDF');
  await page.reload();await page.getByText('Ваш рабочий день',{exact:true}).waitFor();await page.getByRole('button',{name:/Открыть смену/}).click();await page.getByRole('button',{name:'Завершить смену',exact:true}).click();await page.getByRole('button',{name:'Использовать тестовую точку объекта',exact:true}).click();await page.getByRole('button',{name:'Сохранить отметку',exact:true}).click();await page.getByText('Завершение сохранено',{exact:true}).waitFor();assert(errors.length===0,'Browser errors: '+errors.join('; '));console.log('PASS mobile OTP, own shifts, policy, instructions, QR/GPS, offline encrypted incident and attachment across reload, quarantine, signed original download, session isolation, incident review, publication, report PDF and filters');
 }catch(error){console.error('Mobile check:',page.url(),control.url(),errors,JSON.stringify(mobileResponses),JSON.stringify(browserConsole));await page.screenshot({path:path.join(shots,'guard-current-failure.png')}).catch(()=>{});console.error('Mobile current screen:',await page.textContent('body').catch(()=>''));await page.getByRole('tab',{name:/^Журнал/}).click().catch(()=>{});await page.waitForTimeout(300);console.error('Mobile queue:',await page.textContent('body').catch(()=>''));await page.screenshot({path:path.join(shots,'guard-failure.png')}).catch(()=>{});await control.screenshot({path:path.join(shots,'workflow-failure.png')}).catch(()=>{});throw error;}finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
