<?php
declare(strict_types=1);
require __DIR__.'/fixtures/ReleaseLoader-2.0.php';
require dirname(__DIR__).'/backend/src/Core/Autoloader.php';
use Choppro\Stage2\{Config,Db,Migrator,Support,Seeder,DemoData};
$source=dirname(__DIR__);$root=(getenv('CHOPPRO_STORAGE_ROOT')?:sys_get_temp_dir()).'/installed-upgrade';$old=str_repeat('1',40);$head=str_repeat('2',40);$checks=0;
function expect(bool $v,string $m):void{global $checks;if(!$v)throw new RuntimeException($m);$checks++;}
mkdir($root.'/.private/releases/'.$old,0700,true);mkdir($root.'/.private/runtime',0700,true);file_put_contents($root.'/.private/releases/'.$old.'/.release.json','{}');file_put_contents($root.'/.private/current.json',Support::json(['portal'=>$old,'demo'=>$old]));file_put_contents($root.'/.private/runtime/schema.json','{"version":3}');
$config=Config::load();$config['database']['name']='choppro_upgrade';$config['storage']=$root.'/.private/runtime';$connection=new PDO('mysql:host='.$config['database']['host'].';port='.$config['database']['port'],$config['database']['user'],$config['database']['password']);$connection->exec('CREATE DATABASE choppro_upgrade CHARACTER SET utf8mb4');$db=new Db($config);
try{
 $db->pdo->exec('CREATE TABLE cp_schema_migrations(version INT PRIMARY KEY,checksum CHAR(64),applied_at DATETIME)');foreach(glob($source.'/backend/database/stage2/00[1-3]_*.sql')as$file){$sql=file_get_contents($file);foreach(Migrator::statements($sql)as$s)$db->pdo->exec($s);$db->run('INSERT INTO cp_schema_migrations VALUES(?,?,UTC_TIMESTAMP())',[(int)basename($file),hash('sha256',$sql)]);}
 $tenant='11111111-1111-4111-8111-111111111111';$employee='22222222-2222-4222-8222-222222222222';$db->run("INSERT INTO cp_tenants(id,name,slug,inn,status,settings,features,created_at,updated_at,version)VALUES(?,?,?,?,'ACTIVE','{}','{}',UTC_TIMESTAMP(),UTC_TIMESTAMP(),1)",[$tenant,'Сохранённая организация','upgrade','5800000099']);$db->run("INSERT INTO cp_employees(id,tenant_id,name,status,qualification,created_at,updated_at,version)VALUES(?,?,?,'ACTIVE',6,UTC_TIMESTAMP(),UTC_TIMESTAMP(),1)",[$employee,$tenant,'Сохранённый сотрудник']);$db->run('INSERT INTO cp_installation(id,seed_version,seeded_at)VALUES(1,1,UTC_TIMESTAMP())');
 $seed=new Seeder($db,$config);$demo=$seed->add('tenants','tenant-0',['name'=>'ЧОП «ОБЕРЕГ»','slug'=>'obereg','inn'=>'5800000001','status'=>'ACTIVE','settings'=>[],'features'=>['core'=>true,'compliance'=>true,'jobs'=>true]]);
 $seed->add('users','user-0-tenant_admin',['tenant_id'=>$demo,'name'=>'Администратор','role'=>'tenant_admin','scopes'=>[],'is_demo'=>1,'status'=>'ACTIVE']);
 $person=$seed->add('employees','employee-0-0',['tenant_id'=>$demo,'name'=>'Сохранённый тестовый сотрудник','qualification'=>6,'status'=>'ACTIVE','badge'=>'СО-00001']);
 $type=$seed->add('document_types','type-0-0',['tenant_id'=>$demo,'name'=>'Удостоверение охранника']);
 $seed->add('facilities','facility-0-0',['tenant_id'=>$demo,'name'=>'Исходный объект','address'=>'Пенза, ул. Центральная, 10','city'=>'Пенза','lat'=>53.1539,'lng'=>44.9803,'radius'=>150,'polygon'=>[],'timezone'=>'Europe/Moscow']);
 $edited=Seeder::id('facility-0-1');$seed->add('facilities','facility-0-1',['tenant_id'=>$demo,'name'=>'Изменённый объект','address'=>'Пользовательский адрес','city'=>'Пенза','lat'=>53.2,'lng'=>45.1,'radius'=>200,'polygon'=>[],'timezone'=>'Europe/Moscow']);
 $dir=$config['storage'].'/uploads/'.$demo;mkdir($dir,0700,true);$png=base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jN1sAAAAASUVORK5CYII=');file_put_contents($dir.'/demo-document.png',$png);file_put_contents($dir.'/uploaded.pdf','%PDF-user-content');
 $doc=$seed->add('documents','doc-0-0-0',['tenant_id'=>$demo,'name'=>'Исходный документ','employee_id'=>$person,'type_id'=>$type,'number'=>'ДЕМО-0-0-0','issued_at'=>'2025-01-15','expires_at'=>'2030-01-15','status'=>'VALID','scan_status'=>'CLEAN','file_path'=>'demo-document.png','mime'=>'image/png','sha256'=>hash('sha256',$png)]);
 $uploaded=$seed->add('documents','doc-0-0-1',['tenant_id'=>$demo,'name'=>'Загруженный документ','employee_id'=>$person,'type_id'=>$type,'number'=>'Пользовательский номер','status'=>'VALID','scan_status'=>'CLEAN','file_path'=>'uploaded.pdf','mime'=>'application/pdf','sha256'=>hash('sha256','%PDF-user-content')]);
 $db->pdo->exec('CREATE INDEX ix_attendance_assignment_time ON cp_attendance(assignment_id,client_time,status)');$files=[];$probe=new ReleaseLoader($root);foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($source,FilesystemIterator::SKIP_DOTS))as$f){if(!$f->isFile())continue;$path=substr($f->getPathname(),strlen($source)+1);if($probe->allowed($path))$files[$path]=file_get_contents($f->getPathname());}
 $transport=function($url)use($files,&$head){if(str_contains($url,'/commits?'))return Support::json([['sha'=>$head,'commit'=>['tree'=>['sha'=>$head],'message'=>'Изменено приложение','committer'=>['date'=>gmdate('c')]]]]);if(str_contains($url,'/actions/runs'))return Support::json(['workflow_runs'=>[['name'=>'Stage 2 acceptance','conclusion'=>'success','event'=>'push','head_branch'=>'main']]]);if(str_contains($url,'/git/trees/')){$tree=[];foreach($files as$p=>$c)$tree[]=['path'=>$p,'mode'=>'100644','type'=>'blob','size'=>strlen($c),'sha'=>sha1('blob '.strlen($c)."\0".$c)];return Support::json(['tree'=>$tree,'truncated'=>false]);}$p=rawurldecode(implode('/',array_slice(explode('/',parse_url($url,PHP_URL_PATH)),4)));return$files[$p];};
 $loader=new ReleaseLoader($root,$transport);$sync=$loader->sync(true);expect(empty($sync['error']),'Existing loader accepts new complete release');expect($loader->state()['portal']===$head&&$loader->state()['demo']===$old,'Schema gate preserves previous demo');
 define('CHOPPRO_HOST_ROOT',$root);define('CHOPPRO_STORAGE_ROOT',$config['storage']);file_put_contents($root.'/.private/site.php','<?php return '.var_export(['database'=>$config['database']],true).';');require $source.'/acceptance-portal/app/HostUpdate.php';$out=HostUpdate::ensure();expect($out['status']==='ready','Automatic migration from installed schema 3');expect($out['database']['migrations']===['004_operations.sql','005_query_indexes.sql','006_workspace.sql','007_mobile_reporting.sql','008_incident_workflow.sql'],'Only new migrations applied after interrupted index creation');expect(!$out['database']['seeded'],'No repeated demo seeding');expect($loader->state()['demo']===$head,'Demo promoted after migration');expect($db->scalar('SELECT name FROM cp_employees WHERE id=?',[$employee])==='Сохранённый сотрудник','Existing records preserved');$again=HostUpdate::ensure(true);expect($again['status']==='ready'&&$again['database']['migrations']===[],'Repeated database action is idempotent');expect((int)$db->scalar('SELECT COUNT(*) FROM cp_employees')===2,'No duplicate records'); $upgraded=$db->one('SELECT * FROM cp_documents WHERE id=?',[$doc]);expect($upgraded['mime']==='application/pdf'&&$upgraded['number']==='ДЕМО-0-0-0','Legacy test image becomes PDF with existing requisites');expect(str_starts_with(file_get_contents($dir.'/'.$upgraded['file_path']),'%PDF-')&&hash_file('sha256',$dir.'/'.$upgraded['file_path'])===$upgraded['sha256'],'Persisted upgrade PDF matches database');expect($db->scalar('SELECT file_path FROM cp_documents WHERE id=?',[$uploaded])==='uploaded.pdf'&&file_get_contents($dir.'/uploaded.pdf')==='%PDF-user-content','User upload preserved');expect($db->scalar('SELECT address FROM cp_facilities WHERE id=?',[Seeder::id('facility-0-0')])===DemoData::location(0,0)['address'],'Original demo address upgraded');expect($db->scalar('SELECT address FROM cp_facilities WHERE id=?',[$edited])==='Пользовательский адрес','User edited location preserved');expect((int)$db->scalar('SELECT version FROM cp_documents WHERE id=?',[$doc])===2,'Repeated upgrade does not modify version');$head=str_repeat('3',40);$loader->atomic($root.'/.private/sync.json',Support::json(['next_check'=>0]));$automatic=HostUpdate::ensure();expect($automatic['status']==='ready'&&$automatic['release']===$head,'Opening an already installed portal fetches the tested main release');expect($loader->state()['portal']===$head&&$loader->state()['demo']===$head,'Automatic visit update keeps portal and demo coherent');expect($db->scalar('SELECT name FROM cp_employees WHERE id=?',[$employee])==='Сохранённый сотрудник'&&(int)$db->scalar('SELECT version FROM cp_documents WHERE id=?',[$doc])===2,'Automatic visit update preserves records and uploaded documents');echo 'PASS '.$checks." installed-upgrade checks\n";
}finally{$connection->exec('DROP DATABASE choppro_upgrade');}
